package slash

import (
	"bytes"
	"slices"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestRenderHelpIncludesCoreCommands(t *testing.T) {
	var out bytes.Buffer
	RenderHelp(&out)
	require.Contains(t, out.String(), "/status")
	require.Contains(t, out.String(), "/init")
	require.Contains(t, out.String(), "/state")
	require.Contains(t, out.String(), "/terminal-setup")
	require.Contains(t, out.String(), "/terminalSetup")
	require.Contains(t, out.String(), "/remote-env")
	require.Contains(t, out.String(), "/api")
	require.Contains(t, out.String(), "/memory")
	require.Contains(t, out.String(), "/project")
	require.Contains(t, out.String(), "/onboarding")
	require.Contains(t, out.String(), "/env")
	require.Contains(t, out.String(), "/init-verifiers")
	require.Contains(t, out.String(), "/context")
	require.Contains(t, out.String(), "/ctx_viz")
	require.Contains(t, out.String(), "/config")
	require.Contains(t, out.String(), "/settings")
	require.Contains(t, out.String(), "/model")
	require.Contains(t, out.String(), "/advisor")
	require.Contains(t, out.String(), "/max-tokens")
	require.Contains(t, out.String(), "/max-turns")
	require.Contains(t, out.String(), "/btw")
	require.Contains(t, out.String(), "/budget")
	require.Contains(t, out.String(), "/permissions")
	require.Contains(t, out.String(), "/allowed-tools")
	require.Contains(t, out.String(), "/approve")
	require.Contains(t, out.String(), "/yes")
	require.Contains(t, out.String(), "/y")
	require.Contains(t, out.String(), "/deny")
	require.Contains(t, out.String(), "/no")
	require.Contains(t, out.String(), "/n")
	require.Contains(t, out.String(), "/clear")
	require.Contains(t, out.String(), "/new")
	require.Contains(t, out.String(), "/doctor")
	require.Contains(t, out.String(), "/sandbox")
	require.Contains(t, out.String(), "/sandbox-toggle")
	require.Contains(t, out.String(), "/heapdump")
	require.Contains(t, out.String(), "/compact")
	require.Contains(t, out.String(), "/undo")
	require.Contains(t, out.String(), "/caches")
	require.Contains(t, out.String(), "/break-cache")
	require.Contains(t, out.String(), "/usage")
	require.Contains(t, out.String(), "/stats")
	require.Contains(t, out.String(), "/metrics")
	require.Contains(t, out.String(), "/sessions")
	require.Contains(t, out.String(), "/perf-issue")
	require.Contains(t, out.String(), "/think-back")
	require.Contains(t, out.String(), "/thinkback")
	require.Contains(t, out.String(), "/thinkback-play")
	require.Contains(t, out.String(), "/ant-trace")
	require.Contains(t, out.String(), "/rate-limit")
	require.Contains(t, out.String(), "/rate-limit-options")
	require.Contains(t, out.String(), "/mock-limits")
	require.Contains(t, out.String(), "/reset-limits")
	require.Contains(t, out.String(), "/reset")
	require.Contains(t, out.String(), "/plan")
	require.Contains(t, out.String(), "/ultraplan")
	require.Contains(t, out.String(), "/exit-plan")
	require.Contains(t, out.String(), "/diff")
	require.Contains(t, out.String(), "/commit")
	require.Contains(t, out.String(), "/branch")
	require.Contains(t, out.String(), "/green-contract")
	require.Contains(t, out.String(), "/g004-conformance")
	require.Contains(t, out.String(), "/report-schema")
	require.Contains(t, out.String(), "/tag")
	require.Contains(t, out.String(), "/git")
	require.Contains(t, out.String(), "/log")
	require.Contains(t, out.String(), "/changelog")
	require.Contains(t, out.String(), "/release-notes")
	require.Contains(t, out.String(), "/stash")
	require.Contains(t, out.String(), "/blame")
	require.Contains(t, out.String(), "/run")
	require.Contains(t, out.String(), "/node")
	require.Contains(t, out.String(), "/python")
	require.Contains(t, out.String(), "/test")
	require.Contains(t, out.String(), "/build")
	require.Contains(t, out.String(), "/lint")
	require.Contains(t, out.String(), "/symbols")
	require.Contains(t, out.String(), "/diagnostics")
	require.Contains(t, out.String(), "/map")
	require.Contains(t, out.String(), "/references")
	require.Contains(t, out.String(), "/definition")
	require.Contains(t, out.String(), "/hover")
	require.Contains(t, out.String(), "/completion")
	require.Contains(t, out.String(), "/format")
	require.Contains(t, out.String(), "/code-intel")
	require.Contains(t, out.String(), "/notebook-read")
	require.Contains(t, out.String(), "/notebook-edit")
	require.Contains(t, out.String(), "/export")
	require.Contains(t, out.String(), "/history")
	require.Contains(t, out.String(), "/summary")
	require.Contains(t, out.String(), "/todos")
	require.Contains(t, out.String(), "/generateSessionName")
	require.Contains(t, out.String(), "/prompt-history")
	require.Contains(t, out.String(), "/resume")
	require.Contains(t, out.String(), "/rewind")
	require.Contains(t, out.String(), "/checkpoint")
	require.Contains(t, out.String(), "/files")
	require.Contains(t, out.String(), "/search")
	require.Contains(t, out.String(), "/security-review")
	require.Contains(t, out.String(), "/bug")
	require.Contains(t, out.String(), "/review")
	require.Contains(t, out.String(), "/reviewRemote")
	require.Contains(t, out.String(), "/review-remote")
	require.Contains(t, out.String(), "/ultrareview")
	require.Contains(t, out.String(), "/commit-push-pr")
	require.Contains(t, out.String(), "/autofix-pr")
	require.Contains(t, out.String(), "/pr-comments")
	require.Contains(t, out.String(), "/pr_comments")
	require.Contains(t, out.String(), "/marketplace")
	require.Contains(t, out.String(), "/passes")
	require.Contains(t, out.String(), "/focus")
	require.Contains(t, out.String(), "/unfocus")
	require.Contains(t, out.String(), "/add-dir")
	require.Contains(t, out.String(), "/validation")
	require.Contains(t, out.String(), "/workspace")
	require.Contains(t, out.String(), "/cwd")
	require.Contains(t, out.String(), "/output-style")
	require.Contains(t, out.String(), "/language")
	require.Contains(t, out.String(), "/session")
	require.Contains(t, out.String(), "/backfill-sessions")
	require.Contains(t, out.String(), "/skill")
	require.Contains(t, out.String(), "/skills")
	require.Contains(t, out.String(), "/commands")
	require.Contains(t, out.String(), "/hooks")
	require.Contains(t, out.String(), "/mcp")
	require.Contains(t, out.String(), "/acp")
	require.Contains(t, out.String(), "/bridge-kick")
	require.Contains(t, out.String(), "/system-prompt")
	require.Contains(t, out.String(), "/tool-details")
	require.Contains(t, out.String(), "/tokens")
	require.Contains(t, out.String(), "/version")
	require.Contains(t, out.String(), "/templates")
	require.Contains(t, out.String(), "/quit")
	require.Contains(t, out.String(), "/copy")
	require.Contains(t, out.String(), "/agents")
	require.Contains(t, out.String(), "/team")
	require.Contains(t, out.String(), "/tasks")
	require.Contains(t, out.String(), "/bashes")
	require.Contains(t, out.String(), "/background")
	require.Contains(t, out.String(), "/cron")
	require.Contains(t, out.String(), "/plugin")
	require.Contains(t, out.String(), "/plugins")
	require.Contains(t, out.String(), "/marketplace")
	require.Contains(t, out.String(), "/providers")
	require.Contains(t, out.String(), "/profile")
	require.Contains(t, out.String(), "/oauth")
	require.Contains(t, out.String(), "/login")
	require.Contains(t, out.String(), "/oauth-refresh")
	require.Contains(t, out.String(), "/logout")
	require.Contains(t, out.String(), "/voice")
	require.Contains(t, out.String(), "/reasoning")
	require.Contains(t, out.String(), "/remote-setup")
	require.Contains(t, out.String(), "/web-setup")
	require.Contains(t, out.String(), "/remote-control")
	require.Contains(t, out.String(), "/rc")
	require.Contains(t, out.String(), "/bridge")
	require.Contains(t, out.String(), "/desktop")
	require.Contains(t, out.String(), "/mobile")
	require.Contains(t, out.String(), "/reload-plugins")
	require.Contains(t, out.String(), "/upgrade")
	require.Contains(t, out.String(), "/install")
	require.Contains(t, out.String(), "/debug-tool-call")
}

func TestLookupIncludesApprovalAliases(t *testing.T) {
	for _, name := range []string{"/approve", "/yes", "/y", "/deny", "/no", "/n"} {
		spec, ok := Lookup(name)
		require.True(t, ok, name)
		require.Equal(t, name, spec.Name)
		require.False(t, spec.ResumeSupported)
	}
}

func TestDescribeCandidateUsesCommandToken(t *testing.T) {
	spec, ok := DescribeCandidate("/model claude-sonnet")

	require.True(t, ok)
	require.Equal(t, "/model", spec.Name)
	require.Contains(t, spec.Description, "model")

	_, ok = DescribeCandidate("not-a-slash-command")
	require.False(t, ok)
}

func TestCandidatesFiltersSlashCommands(t *testing.T) {
	require.Contains(t, Candidates("/ac"), "/acp")
	require.Contains(t, Candidates("/an"), "/ant-trace --no-request")
	require.Contains(t, Candidates("/au"), "/autofix-pr")

	candidates := Candidates("/co")
	require.Contains(t, candidates, "/compact")
	require.Contains(t, candidates, "/completion")
	require.Contains(t, candidates, "/code-intel")
	require.Contains(t, candidates, "/code-intel lsp actions")
	require.Contains(t, candidates, "/code-intel lsp query ")
	require.Contains(t, candidates, "/code-intel notebook-read ")
	require.Contains(t, candidates, "/commands")
	require.Contains(t, candidates, "/config auth")
	require.Contains(t, Candidates("/cr"), "/cron create ")
	require.Contains(t, Candidates("/bu"), "/bug ")
	require.Contains(t, Candidates("/bu"), "/budget status")
	require.Contains(t, Candidates("/bu"), "/budget set --max-tokens ")
	require.Contains(t, Candidates("/ch"), "/checkpoint ")
	require.Contains(t, Candidates("/ge"), "/generateSessionName")
	require.Contains(t, Candidates("/ge"), "/generateSessionName --rename")
	require.Contains(t, Candidates("/go"), "/good-claude")
	require.Contains(t, Candidates("/sess"), "/sessions")
	require.Contains(t, Candidates("/sessions l"), "/sessions list")
	require.Contains(t, Candidates("/sessions p"), "/sessions prune")
	require.Contains(t, Candidates("/sessions p"), "/sessions prune --confirm")
	require.Contains(t, Candidates("/sessions d"), "/sessions delete ")
	require.Contains(t, Candidates("/g0"), "/g004-conformance")
	require.Contains(t, Candidates("/g0"), "/g004")
	require.Contains(t, Candidates("/gr"), "/green-contract")
	require.Contains(t, Candidates("/gr"), "/green")
	require.Contains(t, Candidates("/cr"), "/cron due")
	require.Contains(t, Candidates("/cr"), "/cron list")
	require.Contains(t, Candidates("/cr"), "/cron run-due")
	require.Contains(t, Candidates("/ra"), "/rate-limit status")
	require.Contains(t, Candidates("/ra"), "/rate-limit-options")
	require.Contains(t, Candidates("/re"), "/report-schema")
	require.Contains(t, Candidates("/pr"), "/profile list")
	require.Contains(t, Candidates("/la"), "/language status")
	require.Contains(t, Candidates("/la"), "/language ")
	require.Contains(t, Candidates("/me"), "/metrics")
	require.Contains(t, Candidates("/me"), "/metrics --json")
	require.Contains(t, Candidates("/ma"), "/marketplace sources")
	require.Contains(t, Candidates("/ma"), "/marketplace browse")
	require.Contains(t, Candidates("/ma"), "/marketplace settings")
	require.Contains(t, Candidates("/mc"), "/mcp auth")
	require.Contains(t, Candidates("/mc"), "/mcp prompts")
	require.Contains(t, Candidates("/mc"), "/mcp resource-templates")
	require.Contains(t, Candidates("/mc"), "/mcp resources")
	require.Contains(t, Candidates("/mc"), "/mcp tools")
	require.Contains(t, Candidates("/mo"), "/mock-limits")
	require.Contains(t, Candidates("/mo"), "/mock-limits --failures 2")
	require.Contains(t, Candidates("/pe"), "/perf-issue")
	require.Contains(t, Candidates("/pe"), "/perf-issue --write")
	require.Contains(t, Candidates("/ne"), "/new")
	require.Contains(t, Candidates("/ne"), "/new --confirm")
	require.Contains(t, Candidates("/no"), "/no")
	require.Contains(t, Candidates("/no"), "/notebook-read ")
	require.Contains(t, Candidates("/no"), "/notebook-edit ")
	require.Contains(t, Candidates("/on"), "/onboarding")
	require.Contains(t, Candidates("/on"), "/onboarding --json")
	require.Contains(t, Candidates("/oa"), "/oauth status")
	require.Contains(t, Candidates("/oa"), "/oauth provider list")
	require.Contains(t, Candidates("/oa"), "/oauth token show")
	require.Contains(t, Candidates("/qu"), "/quit")
	require.Contains(t, Candidates("/rc"), "/rc")
	require.Contains(t, Candidates("/rc"), "/rc serve")
	require.Contains(t, Candidates("/se"), "/settings")
	require.Contains(t, Candidates("/se"), "/settings paths")
	require.Contains(t, Candidates("/sk"), "/skill list")
	require.Contains(t, Candidates("/sk"), "/skill roots")
	require.Contains(t, Candidates("/sk"), "/skill sources")
	require.Contains(t, Candidates("/sk"), "/skill status")
	require.Contains(t, Candidates("/sk"), "/skill enable ")
	require.Contains(t, Candidates("/sk"), "/skill disable ")
	require.Contains(t, Candidates("/sk"), "/skill add ")
	require.Contains(t, Candidates("/sk"), "/skill uninstall ")
	require.Contains(t, Candidates("/sk"), "/skills add ")
	require.Contains(t, Candidates("/sk"), "/skills roots")
	require.Contains(t, Candidates("/sk"), "/skills sources")
	require.Contains(t, Candidates("/sk"), "/skills status")
	require.Contains(t, Candidates("/sk"), "/skills enable ")
	require.Contains(t, Candidates("/sk"), "/skills disable ")
	require.Contains(t, Candidates("/sk"), "/skills install ")
	require.Contains(t, Candidates("/sk"), "/skills uninstall ")
	require.Contains(t, Candidates("/cw"), "/cwd")
	require.Contains(t, Candidates("/cw"), "/cwd ")
	require.Contains(t, Candidates("/wo"), "/workspace")
	require.Contains(t, Candidates("/wo"), "/workspace ")
	require.Contains(t, Candidates("/te"), "/team create ")
	require.Contains(t, Candidates("/te"), "/team list")
	require.Contains(t, Candidates("/te"), "/team status ")
	require.Contains(t, Candidates("/te"), "/team logs ")
	require.Contains(t, Candidates("/te"), "/team watch ")
	require.Contains(t, Candidates("/re"), "/reasoning high")
	require.Contains(t, Candidates("/reviewR"), "/reviewRemote")
	require.Contains(t, Candidates("/review-"), "/review-remote")
	require.Contains(t, Candidates("/re"), "/reset status")
	require.Contains(t, Candidates("/re"), "/reset all --confirm")
	require.NotContains(t, candidates, "/status")
	require.Contains(t, Candidates("/un"), "/undo")
	require.Empty(t, Candidates("co"))
}

func TestResumeSupportedMetadata(t *testing.T) {
	status, ok := Lookup("/status")
	require.True(t, ok)
	require.True(t, status.ResumeSupported)
	require.True(t, SupportsResume("/status"))
	require.True(t, SupportsResume("/STATUS"))

	api, ok := Lookup("/api")
	require.True(t, ok)
	require.True(t, api.ResumeSupported)
	require.Contains(t, api.Usage, "serve")
	require.Contains(t, api.Usage, "listen")
	require.Contains(t, api.Usage, "start")

	mockLimits, ok := Lookup("/mock-limits")
	require.True(t, ok)
	require.True(t, mockLimits.ResumeSupported)
	require.Contains(t, mockLimits.Usage, "status")
	require.Contains(t, mockLimits.Usage, "server")
	require.Contains(t, mockLimits.Usage, "start")

	cron, ok := Lookup("/cron")
	require.True(t, ok)
	require.True(t, cron.ResumeSupported)
	require.Contains(t, cron.Usage, "add")
	require.Contains(t, cron.Usage, "rm")
	require.Contains(t, cron.Usage, "mark")
	require.Contains(t, cron.Usage, "run")

	team, ok := Lookup("/team")
	require.True(t, ok)
	require.True(t, team.ResumeSupported)
	require.Contains(t, team.Usage, "add")
	require.Contains(t, team.Usage, "show")
	require.Contains(t, team.Usage, "stat")
	require.Contains(t, team.Usage, "tail")
	require.Contains(t, team.Usage, "rm")

	skill, ok := Lookup("/skill")
	require.True(t, ok)
	require.True(t, skill.ResumeSupported)
	require.True(t, SupportsResume("/skill"))

	commit, ok := Lookup("/commit")
	require.True(t, ok)
	require.True(t, commit.ResumeSupported)
	require.True(t, SupportsResume("/commit"))

	exitPlanMode, ok := Lookup("/exit_plan_mode")
	require.True(t, ok)
	require.True(t, exitPlanMode.ResumeSupported)
	require.True(t, SupportsResume("/exit_plan_mode"))

	names := ResumeSupportedNames()
	require.Contains(t, names, "/acp")
	require.Contains(t, names, "/advisor")
	require.Contains(t, names, "/autofix-pr")
	require.Contains(t, names, "/backfill-sessions")
	require.Contains(t, names, "/bookmarks")
	require.Contains(t, names, "/brief")
	require.Contains(t, names, "/btw")
	require.Contains(t, names, "/bug")
	require.Contains(t, names, "/capabilities")
	require.Contains(t, names, "/commit")
	require.Contains(t, names, "/commit-push-pr")
	require.Contains(t, names, "/status")
	require.Contains(t, names, "/compact")
	require.Contains(t, names, "/session")
	require.Contains(t, names, "/sessions")
	require.Contains(t, names, "/cron")
	require.Contains(t, names, "/exit_plan_mode")
	require.Contains(t, names, "/hooks")
	require.Contains(t, names, "/models")
	require.Contains(t, names, "/new")
	require.Contains(t, names, "/node")
	require.Contains(t, names, "/python")
	require.Contains(t, names, "/run")
	require.Contains(t, names, "/skill")
	require.Contains(t, names, "/skills")
	require.Contains(t, names, "/subagent")
	require.Contains(t, names, "/system-prompt")
	require.Contains(t, names, "/team")
	require.Contains(t, names, "/terminal-setup")
	require.Contains(t, names, "/terminalSetup")
	require.Contains(t, names, "/tool-details")
	require.Contains(t, names, "/debug-tool-call")
	require.Contains(t, names, "/remote-env")
	require.Contains(t, names, "/remote-setup")
	require.Contains(t, names, "/web-setup")
	require.Contains(t, names, "/setup")
	require.Contains(t, names, "/resume")
	require.Contains(t, names, "/reset")
	require.Contains(t, names, "/sandbox-toggle")
	require.Contains(t, names, "/speak")
	require.Contains(t, names, "/voice")
	require.Contains(t, names, "/plan")
	require.Contains(t, names, "/extra-usage")
	require.Contains(t, names, "/feedback")
	require.Contains(t, names, "/good-claude")
	require.Contains(t, names, "/generateSessionName")
	require.Contains(t, names, "/generate-session-name")
	require.Contains(t, names, "/init-verifiers")
	require.Contains(t, names, "/install")
	require.Contains(t, names, "/install-github-app")
	require.Contains(t, names, "/install-slack-app")
	require.Contains(t, names, "/issue")
	require.Contains(t, names, "/stickers")
	require.Contains(t, names, "/passes")
	require.Contains(t, names, "/pin")
	require.Contains(t, names, "/pr")
	require.Contains(t, names, "/pr-comments")
	require.Contains(t, names, "/pr_comments")
	require.Contains(t, names, "/think-back")
	require.Contains(t, names, "/thinkback")
	require.Contains(t, names, "/thinkback-play")
	require.Contains(t, names, "/unpin")
	require.Contains(t, names, "/reload-plugins")
	require.Contains(t, names, "/heapdump")
	require.Contains(t, names, "/oauth")
	require.Contains(t, names, "/code-intel")
	require.Contains(t, names, "/notebook-edit")
	require.Contains(t, names, "/notebook-read")
	require.Contains(t, names, "/reviewRemote")
	require.Contains(t, names, "/review-remote")
	require.Contains(t, names, "/exit-plan")
	require.Contains(t, names, "/listen")
	require.Contains(t, names, "/test")
	require.Contains(t, names, "/build")
	require.Contains(t, names, "/lint")
	require.Contains(t, names, "/ultraplan")
	require.Contains(t, names, "/undo")
	require.Contains(t, names, "/upgrade")
	require.Greater(t, len(names), 70)

	for _, spec := range ResumeSupportedSpecs() {
		require.True(t, spec.ResumeSupported)
		require.False(t, spec.Hidden)
		require.False(t, spec.Disabled)
	}
}

func TestHookCandidatesIncludeCurrentEvents(t *testing.T) {
	candidates := Candidates("/hooks run ")
	for _, candidate := range []string{
		"/hooks run user-prompt-submit",
		"/hooks run session-start",
		"/hooks run stop",
		"/hooks run pre-compact",
		"/hooks run cwd-changed",
		"/hooks run file-changed",
		"/hooks run instructions-loaded",
	} {
		require.Contains(t, candidates, candidate)
	}
	healthCandidates := Candidates("/hooks health ")
	require.Contains(t, healthCandidates, "/hooks health pre")
	require.Contains(t, healthCandidates, "/hooks health notification")
}

func TestCandidatesWithOptionsIncludeModelAndSessions(t *testing.T) {
	candidates := CandidatesWithOptions("/resume", CandidateOptions{
		Model:            "claude-test",
		ActiveSessionID:  "active-session",
		RecentSessionIDs: []string{"recent-one", "recent-two"},
	})
	require.Contains(t, candidates, "/resume active-session")
	require.Contains(t, candidates, "/resume recent-one")
	require.Contains(t, candidates, "/resume recent-two")

	modelCandidates := CandidatesWithOptions("/model", CandidateOptions{Model: "claude-test"})
	require.Contains(t, modelCandidates, "/model claude-test")
	require.Contains(t, modelCandidates, "/model ")

	modelValueCandidates := CandidatesWithOptions("/model ", CandidateOptions{Model: "claude-test"})
	require.Contains(t, modelValueCandidates, "/model claude-test")
	require.NotContains(t, modelValueCandidates, "/model")
}

func TestCandidatesWithOptionsIncludeExtraCandidates(t *testing.T) {
	candidates := CandidatesWithOptions("/team/", CandidateOptions{Extra: []string{"/team/review ", "/team/audit "}})
	require.Equal(t, []string{"/team/audit ", "/team/review "}, candidates)
}

func TestMenuCandidatesPrioritizeCommandsAndCollapseRuntimeEntries(t *testing.T) {
	candidates := MenuCandidates(CandidateOptions{Extra: []string{
		"/team/review ARGUMENT",
		"/custom ",
		"/.system/internal ",
		"/model custom",
	}})

	require.NotEmpty(t, candidates)
	require.Equal(t, "/add-dir", candidates[0])
	require.Contains(t, candidates, "/help")
	require.Contains(t, candidates, "/model")
	require.Contains(t, candidates, "/usage")
	require.Contains(t, candidates, "/custom")
	require.Contains(t, candidates, "/team/review")
	require.NotContains(t, candidates, "/acp")
	require.NotContains(t, candidates, "/.system/internal")
	require.NotContains(t, candidates, "/team/review ARGUMENT")
	modelIndex := slices.Index(candidates, "/model")
	require.NotContains(t, candidates[modelIndex+1:], "/model")
	require.Less(t, slices.Index(candidates, "/usage"), slices.Index(candidates, "/custom"))
}

func TestFilterCandidatesStablePreservesCategoryOrder(t *testing.T) {
	candidates := []string{"/status", "/skills", "/custom", "/session"}

	require.Equal(t, []string{"/status", "/skills", "/session"}, FilterCandidatesStable("/s", candidates))
	require.Equal(t, []string{"/status"}, FilterCandidatesStable("/ST", candidates))
}

func TestSuggestReturnsNearbySlashCommands(t *testing.T) {
	suggestions := Suggest("/statuz", 3)
	require.Contains(t, suggestions, "/status")
	require.Contains(t, suggestions, "/stats")
	require.LessOrEqual(t, len(suggestions), 3)

	pluginSuggestions := Suggest("plugns", 3)
	require.Contains(t, pluginSuggestions, "/plugin")
	require.Contains(t, pluginSuggestions, "/plugins")

	require.Empty(t, Suggest("zzz", 3))
	require.Empty(t, Suggest("/status", 0))
}

func TestSuggestWithCandidatesIncludesRuntimeSlashCommands(t *testing.T) {
	suggestions := SuggestWithCandidates("/team/reveiw", 3, []string{"/team/review ", "/team/audit "})

	require.Equal(t, "/team/review", suggestions[0])
	require.Contains(t, suggestions, "/team/review")
	require.NotContains(t, suggestions, "/team/review ")
}
