package slash

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestRenderHelpIncludesCoreCommands(t *testing.T) {
	var out bytes.Buffer
	RenderHelp(&out)
	require.Contains(t, out.String(), "/status")
	require.Contains(t, out.String(), "/init")
	require.Contains(t, out.String(), "/state")
	require.Contains(t, out.String(), "/memory")
	require.Contains(t, out.String(), "/project")
	require.Contains(t, out.String(), "/env")
	require.Contains(t, out.String(), "/context")
	require.Contains(t, out.String(), "/config")
	require.Contains(t, out.String(), "/model")
	require.Contains(t, out.String(), "/max-tokens")
	require.Contains(t, out.String(), "/max-turns")
	require.Contains(t, out.String(), "/permissions")
	require.Contains(t, out.String(), "/allowed-tools")
	require.Contains(t, out.String(), "/clear")
	require.Contains(t, out.String(), "/doctor")
	require.Contains(t, out.String(), "/sandbox")
	require.Contains(t, out.String(), "/compact")
	require.Contains(t, out.String(), "/usage")
	require.Contains(t, out.String(), "/rate-limit-options")
	require.Contains(t, out.String(), "/diff")
	require.Contains(t, out.String(), "/commit")
	require.Contains(t, out.String(), "/branch")
	require.Contains(t, out.String(), "/tag")
	require.Contains(t, out.String(), "/git")
	require.Contains(t, out.String(), "/log")
	require.Contains(t, out.String(), "/changelog")
	require.Contains(t, out.String(), "/release-notes")
	require.Contains(t, out.String(), "/stash")
	require.Contains(t, out.String(), "/blame")
	require.Contains(t, out.String(), "/run")
	require.Contains(t, out.String(), "/test")
	require.Contains(t, out.String(), "/build")
	require.Contains(t, out.String(), "/lint")
	require.Contains(t, out.String(), "/symbols")
	require.Contains(t, out.String(), "/diagnostics")
	require.Contains(t, out.String(), "/map")
	require.Contains(t, out.String(), "/references")
	require.Contains(t, out.String(), "/definition")
	require.Contains(t, out.String(), "/hover")
	require.Contains(t, out.String(), "/export")
	require.Contains(t, out.String(), "/history")
	require.Contains(t, out.String(), "/summary")
	require.Contains(t, out.String(), "/todos")
	require.Contains(t, out.String(), "/prompt-history")
	require.Contains(t, out.String(), "/resume")
	require.Contains(t, out.String(), "/rewind")
	require.Contains(t, out.String(), "/files")
	require.Contains(t, out.String(), "/search")
	require.Contains(t, out.String(), "/security-review")
	require.Contains(t, out.String(), "/review")
	require.Contains(t, out.String(), "/focus")
	require.Contains(t, out.String(), "/unfocus")
	require.Contains(t, out.String(), "/add-dir")
	require.Contains(t, out.String(), "/output-style")
	require.Contains(t, out.String(), "/session")
	require.Contains(t, out.String(), "/hooks")
	require.Contains(t, out.String(), "/mcp")
	require.Contains(t, out.String(), "/system-prompt")
	require.Contains(t, out.String(), "/tool-details")
	require.Contains(t, out.String(), "/tokens")
	require.Contains(t, out.String(), "/version")
	require.Contains(t, out.String(), "/templates")
}
