package harness

import (
	"context"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestRunUsesMockProvider(t *testing.T) {
	report, err := Run(context.Background())
	require.NoError(t, err)
	require.NoError(t, ValidateReport(report))
	require.Equal(t, ReportSchemaVersion, report.SchemaVersion)
	require.True(t, report.OK, failedScenarioSummaries(report))
	require.Equal(t, report.Total, report.Passed)
	require.Equal(t, report.Total, report.ScenarioCount)
	require.GreaterOrEqual(t, report.Total, 20)
	require.Equal(t, "actual", report.UsageSummary.Source)
	require.Greater(t, report.UsageSummary.TotalTokens, 0)
	require.Greater(t, report.EstimatedCost, 0.0)
	require.Greater(t, report.RequestCount, 0)
	require.Equal(t, report.RequestCount, scenarioRequestCountTotal(report.Scenarios))
	require.GreaterOrEqual(t, len(report.Coverage), 8)
	require.Equal(t, report.Total, categoryCoverageTotal(report.Coverage))
	for _, scenario := range report.Scenarios {
		require.NotEmpty(t, scenario.Description, scenario.Name)
		require.NotEmpty(t, scenario.ParityRefs, scenario.Name)
		require.Len(t, scenario.ToolUses, scenario.ToolCalls, scenario.Name)
		require.LessOrEqual(t, scenario.ToolErrorCount, scenario.ToolCalls, scenario.Name)
		_, hasMetadata := scenarioMetadataByName[scenario.Name]
		require.True(t, hasMetadata, scenario.Name)
	}
	fileTools := findCategory(t, report, "file-tools")
	require.True(t, fileTools.OK)
	require.Equal(t, 5, fileTools.Total)
	require.ElementsMatch(t, []string{"edit_glob_ls_roundtrip", "grep_chunk_assembly", "multi_edit_apply_patch_roundtrip", "read_file_roundtrip", "write_file_allowed"}, fileTools.Scenarios)
	hooks := findCategory(t, report, "hooks")
	require.Equal(t, 6, hooks.Total)
	permissions := findCategory(t, report, "permissions")
	require.Equal(t, 4, permissions.Total)

	readFile := findScenario(t, report, "read_file_roundtrip")
	require.Equal(t, "file-tools", readFile.Category)
	require.NotEmpty(t, readFile.Description)
	require.Contains(t, readFile.ParityRefs, "File tools")
	require.Equal(t, 2, readFile.RequestCount)
	require.Equal(t, []string{"read_file"}, readFile.ToolUses)
	require.Equal(t, 0, readFile.ToolErrorCount)
	require.Equal(t, "codog harness ok", readFile.FinalMessage)
	require.Contains(t, readFile.Output, "codog harness ok")
	require.Equal(t, 2, readFile.Iterations)
	require.Equal(t, 1, readFile.ToolCalls)
	require.GreaterOrEqual(t, readFile.MessageCount, 4)

	editGlobLS := findScenario(t, report, "edit_glob_ls_roundtrip")
	require.True(t, editGlobLS.OK)
	require.Equal(t, "file-tools", editGlobLS.Category)
	require.Equal(t, []string{"edit_file", "glob", "ls"}, editGlobLS.ToolUses)
	require.Equal(t, 3, editGlobLS.ToolCalls)
	require.Contains(t, editGlobLS.FinalMessage, "edit glob ls harness ok")

	multiEditApplyPatch := findScenario(t, report, "multi_edit_apply_patch_roundtrip")
	require.True(t, multiEditApplyPatch.OK)
	require.Equal(t, "file-tools", multiEditApplyPatch.Category)
	require.Equal(t, []string{"multi_edit", "apply_patch"}, multiEditApplyPatch.ToolUses)
	require.Equal(t, 2, multiEditApplyPatch.ToolCalls)
	require.Contains(t, multiEditApplyPatch.FinalMessage, "multi edit apply patch harness ok")

	attachments := findScenario(t, report, "prompt_attachments_roundtrip")
	require.Equal(t, "attachments", attachments.Category)
	require.True(t, attachments.OK)
	require.Equal(t, 0, attachments.ToolCalls)
	require.Contains(t, attachments.Output, "attachment harness ok")

	directoryAttachment := findScenario(t, report, "prompt_directory_attachment_roundtrip")
	require.Equal(t, "attachments", directoryAttachment.Category)
	require.True(t, directoryAttachment.OK)
	require.Equal(t, 0, directoryAttachment.ToolCalls)
	require.Equal(t, 1, directoryAttachment.RequestCount)
	require.Equal(t, "directory attachment harness ok", directoryAttachment.FinalMessage)
	require.Contains(t, directoryAttachment.Output, `"kind":"prompt_directory_attachment"`)
	require.Contains(t, directoryAttachment.Output, `"files":2`)
	require.Contains(t, directoryAttachment.Output, `"nested":true`)
	require.Contains(t, directoryAttachment.Output, `"skipped_binary":true`)
	require.Contains(t, directoryAttachment.Output, `"text_rendered":true`)
	attachmentsCategory := findCategory(t, report, "attachments")
	require.True(t, attachmentsCategory.OK)
	require.Equal(t, 2, attachmentsCategory.Total)
	require.ElementsMatch(t, []string{"prompt_attachments_roundtrip", "prompt_directory_attachment_roundtrip"}, attachmentsCategory.Scenarios)

	writeDenied := findScenario(t, report, "write_file_denied")
	require.True(t, writeDenied.OK)
	require.Equal(t, 1, writeDenied.ToolCalls)
	require.Equal(t, []string{"write_file"}, writeDenied.ToolUses)
	require.Equal(t, 1, writeDenied.ToolErrorCount)

	preToolHook := findScenario(t, report, "pre_tool_hook_updates_input")
	require.True(t, preToolHook.OK)
	require.Equal(t, 1, preToolHook.ToolCalls)
	require.Contains(t, preToolHook.Output, "pre hook harness ok")

	userPromptHook := findScenario(t, report, "user_prompt_hook_adds_context")
	require.True(t, userPromptHook.OK)
	require.Equal(t, []int{2}, userPromptHook.RequestMessageCounts)
	require.Contains(t, userPromptHook.Output, "prompt hook harness ok")

	stopHook := findScenario(t, report, "stop_hook_adds_feedback")
	require.True(t, stopHook.OK)
	require.Contains(t, stopHook.Output, "stop hook harness ok")

	postToolHook := findScenario(t, report, "post_tool_hook_blocks_result")
	require.True(t, postToolHook.OK)
	require.Equal(t, 1, postToolHook.ToolCalls)
	require.Contains(t, postToolHook.Output, "post hook block harness ok")

	postToolFeedback := findScenario(t, report, "post_tool_hook_adds_feedback")
	require.True(t, postToolFeedback.OK)
	require.Equal(t, 1, postToolFeedback.ToolCalls)
	require.Contains(t, postToolFeedback.Output, "post feedback harness ok")

	fileChangedFeedback := findScenario(t, report, "file_changed_hook_adds_feedback")
	require.True(t, fileChangedFeedback.OK)
	require.Equal(t, 1, fileChangedFeedback.ToolCalls)
	require.Contains(t, fileChangedFeedback.Output, "file changed feedback harness ok")

	grepChunks := findScenario(t, report, "grep_chunk_assembly")
	require.True(t, grepChunks.OK)
	require.Equal(t, 1, grepChunks.ToolCalls)
	require.Contains(t, grepChunks.Output, "grep chunk harness ok")

	bashBackgroundOutput := findScenario(t, report, "bash_background_output_roundtrip")
	require.True(t, bashBackgroundOutput.OK)
	require.Equal(t, "bash", bashBackgroundOutput.Category)
	require.Equal(t, []string{"bash", "bash_output"}, bashBackgroundOutput.ToolUses)
	require.Equal(t, 2, bashBackgroundOutput.ToolCalls)
	require.Equal(t, 0, bashBackgroundOutput.ToolErrorCount)
	require.Contains(t, bashBackgroundOutput.Output, "background-harness")
	require.Contains(t, bashBackgroundOutput.Output, "bash background output harness ok")

	bashKill := findScenario(t, report, "bash_kill_roundtrip")
	require.True(t, bashKill.OK)
	require.Equal(t, "bash", bashKill.Category)
	require.Equal(t, []string{"bash", "bash_output", "kill_bash", "bash_output"}, bashKill.ToolUses)
	require.Equal(t, 4, bashKill.ToolCalls)
	require.Equal(t, 0, bashKill.ToolErrorCount)
	require.Contains(t, bashKill.Output, `"status": "stopped"`)
	require.Contains(t, bashKill.Output, "bash kill harness ok")

	powerShellStdout := findScenario(t, report, "powershell_stdout_roundtrip")
	require.True(t, powerShellStdout.OK)
	require.Equal(t, "powershell", powerShellStdout.Category)
	require.Equal(t, []string{"powershell"}, powerShellStdout.ToolUses)
	require.Equal(t, 1, powerShellStdout.ToolCalls)
	require.Equal(t, 0, powerShellStdout.ToolErrorCount)
	require.Contains(t, powerShellStdout.Output, "powershell harness ok")

	bashApproved := findScenario(t, report, "bash_permission_prompt_approved")
	require.True(t, bashApproved.OK)
	require.Equal(t, 1, bashApproved.ToolCalls)
	require.Contains(t, bashApproved.Output, "bash approved harness ok")

	bashDenied := findScenario(t, report, "bash_permission_prompt_denied")
	require.True(t, bashDenied.OK)
	require.Equal(t, 1, bashDenied.ToolCalls)
	require.Contains(t, bashDenied.Output, "bash denied harness ok")

	permissionScope := findScenario(t, report, "permission_scope_denial_roundtrip")
	require.True(t, permissionScope.OK)
	require.Equal(t, "permissions", permissionScope.Category)
	require.Equal(t, 3, permissionScope.ToolCalls)
	require.Equal(t, 2, permissionScope.ToolErrorCount)
	require.Equal(t, []string{"testing_permission", "bash", "read_file"}, permissionScope.ToolUses)
	require.Equal(t, "permission scope denial harness ok", permissionScope.FinalMessage)
	require.Contains(t, permissionScope.Output, `"kind":"permission_scope_denial"`)
	require.Contains(t, permissionScope.Output, `"reason":"bash_validation"`)
	require.Contains(t, permissionScope.Output, `"decision_reason":"bash_validation"`)
	require.Contains(t, permissionScope.Output, `"decision_allowed":false`)
	require.Contains(t, permissionScope.Output, `"path resolves outside workspace scope"`)
	require.Contains(t, permissionScope.Output, "path escapes workspace scope")

	bashTruncation := findScenario(t, report, "bash_output_truncation_roundtrip")
	require.True(t, bashTruncation.OK)
	require.Equal(t, 1, bashTruncation.ToolCalls)
	require.Equal(t, []string{"bash"}, bashTruncation.ToolUses)
	require.Equal(t, 0, bashTruncation.ToolErrorCount)
	require.Contains(t, bashTruncation.Description, "truncated")
	require.Contains(t, bashTruncation.Output, "bash truncation harness ok")

	sandboxBypass := findScenario(t, report, "sandbox_bypass_status_roundtrip")
	require.True(t, sandboxBypass.OK)
	require.Equal(t, "sandbox", sandboxBypass.Category)
	require.Equal(t, 1, sandboxBypass.ToolCalls)
	require.Equal(t, []string{"bash"}, sandboxBypass.ToolUses)
	require.Contains(t, sandboxBypass.Output, `"dangerouslyDisableSandbox": true`)
	require.Contains(t, sandboxBypass.Output, `"resolution_status": "disabled"`)
	require.Contains(t, sandboxBypass.Output, "sandbox-bypass-ok")
	sandboxCategory := findCategory(t, report, "sandbox")
	require.True(t, sandboxCategory.OK)
	require.Equal(t, 1, sandboxCategory.Total)
	require.ElementsMatch(t, []string{"sandbox_bypass_status_roundtrip"}, sandboxCategory.Scenarios)

	policySafety := findScenario(t, report, "policy_update_sandbox_roundtrip")
	require.True(t, policySafety.OK)
	require.Equal(t, "policy-safety", policySafety.Category)
	require.Equal(t, 0, policySafety.ToolCalls)
	require.Equal(t, 5, policySafety.RequestCount)
	require.Equal(t, "policy update sandbox harness ok", policySafety.FinalMessage)
	require.Contains(t, policySafety.Output, `"kind":"policy_update_sandbox"`)
	require.Contains(t, policySafety.Output, `"actions":["merge_forward"]`)
	require.Contains(t, policySafety.Output, `"events":1`)
	require.Contains(t, policySafety.Output, `"active":true`)
	require.Contains(t, policySafety.Output, `"signature_valid":true`)
	require.Contains(t, policySafety.Output, `"download_verified":true`)
	require.Contains(t, policySafety.Output, `"rolled_back":true`)

	policyApproval := findScenario(t, report, "policy_approval_roundtrip")
	require.True(t, policyApproval.OK)
	require.Equal(t, "policy-safety", policyApproval.Category)
	require.Equal(t, 10, policyApproval.ToolCalls)
	require.Equal(t, 10, policyApproval.RequestCount)
	require.Equal(t, []string{
		"policy_evaluate",
		"policy_evaluate",
		"policy_evaluate",
		"approval_token",
		"approval_token",
		"approval_token",
		"approval_token",
		"approval_token",
		"approval_token",
		"approval_token",
	}, policyApproval.ToolUses)
	require.Equal(t, "policy approval harness ok", policyApproval.FinalMessage)
	require.Contains(t, policyApproval.Output, `"kind":"policy_approval"`)
	require.Contains(t, policyApproval.Output, `"escalation_action":"escalate"`)
	require.Contains(t, policyApproval.Output, `"blocked_status":"blocked_by_policy"`)
	require.Contains(t, policyApproval.Output, `"blocked_reason":"main_push_forbidden"`)
	require.Contains(t, policyApproval.Output, `"fallback":["create_branch","open_pr"]`)
	require.Contains(t, policyApproval.Output, `"pending":"approval_pending"`)
	require.Contains(t, policyApproval.Output, `"pending_verify_error":"approval_pending"`)
	require.Contains(t, policyApproval.Output, `"scope_commit":"abc123"`)
	require.Contains(t, policyApproval.Output, `"requesting_actor":"release-lead"`)
	require.Contains(t, policyApproval.Output, `"executing_actor":"release-bot"`)
	require.Contains(t, policyApproval.Output, `"execution_mode":"delegated_execution"`)
	require.Contains(t, policyApproval.Output, `"replay_nonce":"codog-replay-`)
	require.Contains(t, policyApproval.Output, `"ledger_replay_nonce":"codog-replay-`)
	require.Contains(t, policyApproval.Output, `"verified":"approval_granted"`)
	require.Contains(t, policyApproval.Output, `"delegated":true`)
	require.Contains(t, policyApproval.Output, `"consumed":"approval_consumed"`)
	require.Contains(t, policyApproval.Output, `"ledger_state":"consumed"`)
	require.Contains(t, policyApproval.Output, `"ledger_usable":false`)
	require.Contains(t, policyApproval.Output, `"remaining_uses":0`)
	require.Contains(t, policyApproval.Output, `"replay_error":"approval_already_consumed"`)
	require.Contains(t, policyApproval.Output, `"last_audit_error":"approval_already_consumed"`)
	require.Contains(t, policyApproval.Output, `"delegation_hop_count":4`)

	policySafetyCategory := findCategory(t, report, "policy-safety")
	require.True(t, policySafetyCategory.OK)
	require.Equal(t, 2, policySafetyCategory.Total)
	require.ElementsMatch(t, []string{"policy_update_sandbox_roundtrip", "policy_approval_roundtrip"}, policySafetyCategory.Scenarios)

	notebook := findScenario(t, report, "notebook_read_edit_roundtrip")
	require.True(t, notebook.OK)
	require.Equal(t, "notebook", notebook.Category)
	require.Equal(t, 4, notebook.ToolCalls)
	require.Equal(t, []string{"notebook_read", "notebook_edit", "notebook_edit", "notebook_read"}, notebook.ToolUses)
	require.Contains(t, notebook.Output, `"kind": "notebook_read"`)
	require.Contains(t, notebook.Output, `"kind": "notebook_edit"`)
	require.Contains(t, notebook.Output, "# Renamed")
	require.Contains(t, notebook.Output, "print(2)")
	notebookCategory := findCategory(t, report, "notebook")
	require.True(t, notebookCategory.OK)
	require.Equal(t, 1, notebookCategory.Total)
	require.ElementsMatch(t, []string{"notebook_read_edit_roundtrip"}, notebookCategory.Scenarios)

	webAccess := findScenario(t, report, "web_access_roundtrip")
	require.True(t, webAccess.OK)
	require.Equal(t, "web-access", webAccess.Category)
	require.Equal(t, 2, webAccess.ToolCalls)
	require.Equal(t, []string{"web_fetch", "web_search"}, webAccess.ToolUses)
	require.Contains(t, webAccess.Output, `"title": "Codog Web Parity"`)
	require.Contains(t, webAccess.Output, `"summary": "Title: Codog Web Parity"`)
	require.Contains(t, webAccess.Output, `"tool_use_id": "web_search_1"`)
	require.Contains(t, webAccess.Output, `"url": "https://example.com/codog"`)
	require.NotContains(t, webAccess.Output, "Blocked result")
	webAccessCategory := findCategory(t, report, "web-access")
	require.True(t, webAccessCategory.OK)
	require.Equal(t, 2, webAccessCategory.Total)
	require.ElementsMatch(t, []string{"web_access_limits_roundtrip", "web_access_roundtrip"}, webAccessCategory.Scenarios)

	webAccessLimits := findScenario(t, report, "web_access_limits_roundtrip")
	require.True(t, webAccessLimits.OK)
	require.Equal(t, "web-access", webAccessLimits.Category)
	require.Equal(t, 2, webAccessLimits.ToolCalls)
	require.Equal(t, []string{"web_fetch", "web_search"}, webAccessLimits.ToolUses)
	require.Contains(t, webAccessLimits.Output, `"truncated": true`)
	require.Contains(t, webAccessLimits.Output, `"hits": []`)
	require.Contains(t, webAccessLimits.Output, "No web search results matched")
	require.NotContains(t, webAccessLimits.Output, "Filtered docs")

	gitWorkspace := findScenario(t, report, "git_workspace_roundtrip")
	require.True(t, gitWorkspace.OK)
	require.Equal(t, "git-workspace", gitWorkspace.Category)
	require.Equal(t, 6, gitWorkspace.ToolCalls)
	require.Equal(t, []string{"git_status", "git_diff", "git_log", "git_show", "git_blame", "branch_freshness"}, gitWorkspace.ToolUses)
	require.Contains(t, gitWorkspace.Output, "notes.txt")
	require.Contains(t, gitWorkspace.Output, "+beta")
	require.Contains(t, gitWorkspace.Output, "initial notes")
	require.Contains(t, gitWorkspace.Output, `"status": "stale"`)
	require.Contains(t, gitWorkspace.Output, `"verification_blocked": true`)

	gitPreserveState := findScenario(t, report, "git_preserve_state_roundtrip")
	require.True(t, gitPreserveState.OK)
	require.Equal(t, "git-workspace", gitPreserveState.Category)
	require.Equal(t, 0, gitPreserveState.ToolCalls)
	require.Equal(t, "git preserve state harness ok", gitPreserveState.FinalMessage)
	require.Contains(t, gitPreserveState.Output, `"kind":"git_preserve_state"`)
	require.Contains(t, gitPreserveState.Output, `"remote_base":"origin/main"`)
	require.Contains(t, gitPreserveState.Output, `"branch_name":"main"`)
	require.Contains(t, gitPreserveState.Output, `"patch_has_feature":true`)
	require.Contains(t, gitPreserveState.Output, `"patch_has_dirty":true`)
	require.Contains(t, gitPreserveState.Output, `"format_patch":true`)
	require.Contains(t, gitPreserveState.Output, `"share_sidecar":true`)
	require.Contains(t, gitPreserveState.Output, `"untracked_files":1`)

	worktreeLifecycle := findScenario(t, report, "worktree_lifecycle_roundtrip")
	require.True(t, worktreeLifecycle.OK)
	require.Equal(t, "git-workspace", worktreeLifecycle.Category)
	require.Equal(t, 2, worktreeLifecycle.ToolCalls)
	require.Equal(t, []string{"enter_worktree", "exit_worktree"}, worktreeLifecycle.ToolUses)
	require.Contains(t, worktreeLifecycle.Output, `"operation": "enter"`)
	require.Contains(t, worktreeLifecycle.Output, `"operation": "exit"`)
	require.Contains(t, worktreeLifecycle.Output, "worktree lifecycle harness ok")
	gitWorkspaceCategory := findCategory(t, report, "git-workspace")
	require.True(t, gitWorkspaceCategory.OK)
	require.Equal(t, 3, gitWorkspaceCategory.Total)
	require.ElementsMatch(t, []string{"git_workspace_roundtrip", "git_preserve_state_roundtrip", "worktree_lifecycle_roundtrip"}, gitWorkspaceCategory.Scenarios)

	planTodo := findScenario(t, report, "plan_todo_roundtrip")
	require.True(t, planTodo.OK)
	require.Equal(t, "planning", planTodo.Category)
	require.Equal(t, 4, planTodo.ToolCalls)
	require.Equal(t, []string{"enter_plan_mode", "todo_write", "todo_read", "exit_plan_mode"}, planTodo.ToolUses)
	require.Contains(t, planTodo.Output, `"action": "enter"`)
	require.Contains(t, planTodo.Output, `"status": "active"`)
	require.Contains(t, planTodo.Output, `"content": "write focused parity test"`)
	require.Contains(t, planTodo.Output, `"action": "exit"`)
	require.Contains(t, planTodo.Output, `"status": "inactive"`)
	planTodoCategory := findCategory(t, report, "planning")
	require.True(t, planTodoCategory.OK)
	require.Equal(t, 2, planTodoCategory.Total)
	require.ElementsMatch(t, []string{"plan_todo_roundtrip", "todo_completion_verification_roundtrip"}, planTodoCategory.Scenarios)

	todoCompletion := findScenario(t, report, "todo_completion_verification_roundtrip")
	require.True(t, todoCompletion.OK)
	require.Equal(t, "planning", todoCompletion.Category)
	require.Equal(t, 3, todoCompletion.ToolCalls)
	require.Equal(t, []string{"todo_write", "todo_write", "todo_read"}, todoCompletion.ToolUses)
	require.Contains(t, todoCompletion.Output, `"verificationNudgeNeeded": true`)
	require.Contains(t, todoCompletion.Output, `"total": 0`)
	require.Contains(t, todoCompletion.FinalMessage, "todo completion verification harness ok")

	lspStatic := findScenario(t, report, "lsp_static_roundtrip")
	require.True(t, lspStatic.OK)
	require.Equal(t, "code-intelligence", lspStatic.Category)
	require.Equal(t, 52, lspStatic.ToolCalls)
	expectedLSPToolUses := make([]string, 52)
	for i := range expectedLSPToolUses {
		expectedLSPToolUses[i] = "lsp"
	}
	require.Equal(t, expectedLSPToolUses, lspStatic.ToolUses)
	require.Contains(t, lspStatic.Output, `"action": "symbols"`)
	require.Contains(t, lspStatic.Output, `"action": "workspace-symbol"`)
	require.Contains(t, lspStatic.Output, `"action": "workspace-symbol-resolve"`)
	require.Contains(t, lspStatic.Output, `"action": "declaration"`)
	require.Contains(t, lspStatic.Output, `"action": "type-definition"`)
	require.Contains(t, lspStatic.Output, `"action": "document-highlight"`)
	require.Contains(t, lspStatic.Output, `"action": "folding-range"`)
	require.Contains(t, lspStatic.Output, `"action": "selection-range"`)
	require.Contains(t, lspStatic.Output, `"action": "moniker"`)
	require.Contains(t, lspStatic.Output, `"action": "linked-editing-range"`)
	require.Contains(t, lspStatic.Output, `"action": "document-link"`)
	require.Contains(t, lspStatic.Output, `"action": "document-link-resolve"`)
	require.Contains(t, lspStatic.Output, `"action": "document-color"`)
	require.Contains(t, lspStatic.Output, `"action": "color-presentation"`)
	require.Contains(t, lspStatic.Output, `"action": "inlay-hint"`)
	require.Contains(t, lspStatic.Output, `"action": "inlay-hint-resolve"`)
	require.Contains(t, lspStatic.Output, `"action": "signature-help"`)
	require.Contains(t, lspStatic.Output, `"action": "code-lens"`)
	require.Contains(t, lspStatic.Output, `"action": "code-lens-resolve"`)
	require.Contains(t, lspStatic.Output, `"action": "semantic-tokens"`)
	require.Contains(t, lspStatic.Output, `"action": "semantic-tokens-range"`)
	require.Contains(t, lspStatic.Output, `"action": "semantic-tokens-delta"`)
	require.Contains(t, lspStatic.Output, `"action": "prepare-rename"`)
	require.Contains(t, lspStatic.Output, `"action": "rename"`)
	require.Contains(t, lspStatic.Output, `"action": "prepare-call-hierarchy"`)
	require.Contains(t, lspStatic.Output, `"action": "call-hierarchy-incoming"`)
	require.Contains(t, lspStatic.Output, `"action": "call-hierarchy-outgoing"`)
	require.Contains(t, lspStatic.Output, `"action": "prepare-type-hierarchy"`)
	require.Contains(t, lspStatic.Output, `"action": "type-hierarchy-supertypes"`)
	require.Contains(t, lspStatic.Output, `"action": "type-hierarchy-subtypes"`)
	require.Contains(t, lspStatic.Output, `"action": "implementation"`)
	require.Contains(t, lspStatic.Output, `"name": "RunFast"`)
	require.Contains(t, lspStatic.Output, `"action": "references"`)
	require.Contains(t, lspStatic.Output, `"action": "completion-item-resolve"`)
	require.Contains(t, lspStatic.Output, `"action": "range-format"`)
	require.Contains(t, lspStatic.Output, `"action": "on-type-format"`)
	require.Contains(t, lspStatic.Output, `"action": "will-save"`)
	require.Contains(t, lspStatic.Output, `"action": "code-action"`)
	require.Contains(t, lspStatic.Output, `"action": "code-action-resolve"`)
	require.Contains(t, lspStatic.Output, `"kind": "source.organizeImports"`)
	require.Contains(t, lspStatic.Output, `"organize_imports": {`)
	require.Contains(t, lspStatic.Output, `"kind": "source.fixAll"`)
	require.Contains(t, lspStatic.Output, `"fix_all": {`)
	require.Contains(t, lspStatic.Output, `"action": "inline-value"`)
	require.Contains(t, lspStatic.Output, `"action": "execute-command"`)
	require.Contains(t, lspStatic.Output, `"action": "document-diagnostic"`)
	require.Contains(t, lspStatic.Output, `"action": "workspace-diagnostic"`)
	require.Contains(t, lspStatic.Output, `"action": "diagnostics"`)
	require.Contains(t, lspStatic.Output, `"path": "pkg/broken.go"`)
	require.Contains(t, lspStatic.Output, "MissingSymbol")
	require.Contains(t, lspStatic.Output, `"action": "format"`)

	lspMetadata := findScenario(t, report, "lsp_cli_metadata_roundtrip")
	require.True(t, lspMetadata.OK)
	require.Equal(t, "code-intelligence", lspMetadata.Category)
	require.Equal(t, 0, lspMetadata.ToolCalls)
	require.Equal(t, 4, lspMetadata.RequestCount)
	require.Equal(t, "lsp cli metadata harness ok", lspMetadata.FinalMessage)
	require.Contains(t, lspMetadata.Output, `"kind":"lsp_cli_metadata"`)
	require.Contains(t, lspMetadata.Output, `"has_go":true`)
	require.Contains(t, lspMetadata.Output, `"has_rust":true`)
	require.Contains(t, lspMetadata.Output, `"servers":0`)
	require.Contains(t, lspMetadata.Output, `"text_rendered":true`)
	lspStaticCategory := findCategory(t, report, "code-intelligence")
	require.True(t, lspStaticCategory.OK)
	require.Equal(t, 2, lspStaticCategory.Total)
	require.ElementsMatch(t, []string{"lsp_static_roundtrip", "lsp_cli_metadata_roundtrip"}, lspStaticCategory.Scenarios)

	pluginTool := findScenario(t, report, "plugin_tool_roundtrip")
	require.True(t, pluginTool.OK)
	require.Equal(t, 1, pluginTool.ToolCalls)
	require.Contains(t, pluginTool.Output, "plugin harness ok")

	workflow := findScenario(t, report, "command_skill_template_roundtrip")
	require.True(t, workflow.OK)
	require.Equal(t, "command-workflows", workflow.Category)
	require.Equal(t, 0, workflow.ToolCalls)
	require.Equal(t, 3, workflow.RequestCount)
	require.Equal(t, "command skill template harness ok", workflow.FinalMessage)
	require.Contains(t, workflow.Output, `"kind":"command_skill_template"`)
	require.Contains(t, workflow.Output, `"rendered":"Review src/main.go for session session-123."`)
	require.Contains(t, workflow.Output, `"matches_src":true`)
	require.Contains(t, workflow.Output, `"rendered":"Release 1.0.0 for codog."`)

	skillActivation := findScenario(t, report, "skill_activation_roundtrip")
	require.True(t, skillActivation.OK)
	require.Equal(t, "command-workflows", skillActivation.Category)
	require.Equal(t, 0, skillActivation.ToolCalls)
	require.Equal(t, 5, skillActivation.RequestCount)
	require.Equal(t, "skill activation harness ok", skillActivation.FinalMessage)
	require.Contains(t, skillActivation.Output, `"kind":"skill_activation"`)
	require.Contains(t, skillActivation.Output, `"enabled":["review"]`)
	require.Contains(t, skillActivation.Output, `"added":["review"]`)
	require.Contains(t, skillActivation.Output, `"resolved":["review"]`)
	require.Contains(t, skillActivation.Output, `"removed":["review"]`)
	require.Contains(t, skillActivation.Output, `"final_enabled":[]`)
	require.Contains(t, skillActivation.Output, `"path_persisted":true`)
	require.Contains(t, skillActivation.Output, `"text_rendered":true`)
	require.Contains(t, skillActivation.Output, `"config_unset":true`)

	onboardingBookmarks := findScenario(t, report, "onboarding_bookmarks_roundtrip")
	require.True(t, onboardingBookmarks.OK)
	require.Equal(t, "command-workflows", onboardingBookmarks.Category)
	require.Equal(t, 0, onboardingBookmarks.ToolCalls)
	require.Equal(t, 2, onboardingBookmarks.RequestCount)
	require.Equal(t, "onboarding bookmarks harness ok", onboardingBookmarks.FinalMessage)
	require.Contains(t, onboardingBookmarks.Output, `"kind":"onboarding_bookmarks"`)
	require.Contains(t, onboardingBookmarks.Output, `"primary_language":"Go"`)
	require.Contains(t, onboardingBookmarks.Output, `"created":"review-start"`)
	require.Contains(t, onboardingBookmarks.Output, `"deleted":"review-start"`)
	require.Contains(t, onboardingBookmarks.Output, `"remaining":0`)
	workflowCategory := findCategory(t, report, "command-workflows")
	require.True(t, workflowCategory.OK)
	require.Equal(t, 3, workflowCategory.Total)
	require.ElementsMatch(t, []string{"command_skill_template_roundtrip", "skill_activation_roundtrip", "onboarding_bookmarks_roundtrip"}, workflowCategory.Scenarios)

	memoryLifecycle := findScenario(t, report, "memory_lifecycle_roundtrip")
	require.True(t, memoryLifecycle.OK)
	require.Equal(t, "context-management", memoryLifecycle.Category)
	require.Equal(t, 0, memoryLifecycle.ToolCalls)
	require.Equal(t, 6, memoryLifecycle.RequestCount)
	require.Equal(t, "memory lifecycle harness ok", memoryLifecycle.FinalMessage)
	require.Contains(t, memoryLifecycle.Output, `"kind":"memory_lifecycle"`)
	require.Contains(t, memoryLifecycle.Output, `"instruction_files":1`)
	require.Contains(t, memoryLifecycle.Output, `"query":"verification commands"`)
	require.Contains(t, memoryLifecycle.Output, `"contains":true`)
	require.Contains(t, memoryLifecycle.Output, `"created":true`)
	require.Contains(t, memoryLifecycle.Output, `"reset_count":1`)

	directoryReference := findScenario(t, report, "prompt_directory_reference_roundtrip")
	require.True(t, directoryReference.OK)
	require.Equal(t, "context-management", directoryReference.Category)
	require.Equal(t, 0, directoryReference.ToolCalls)
	require.Equal(t, 1, directoryReference.RequestCount)
	require.Equal(t, "directory reference harness ok", directoryReference.FinalMessage)
	require.Contains(t, directoryReference.Output, `"kind":"prompt_directory_reference"`)
	require.Contains(t, directoryReference.Output, `"files":2`)
	require.Contains(t, directoryReference.Output, `"has_directory":true`)
	require.Contains(t, directoryReference.Output, `"has_nested":true`)
	require.Contains(t, directoryReference.Output, `"skipped_binary":true`)

	sessionSummary := findScenario(t, report, "session_summary_roundtrip")
	require.True(t, sessionSummary.OK)
	require.Equal(t, "context-management", sessionSummary.Category)
	require.Equal(t, 0, sessionSummary.ToolCalls)
	require.Equal(t, 2, sessionSummary.RequestCount)
	require.Equal(t, "session summary harness ok", sessionSummary.FinalMessage)
	require.Contains(t, sessionSummary.Output, `"kind":"session_summary"`)
	require.Contains(t, sessionSummary.Output, `"message_count":5`)
	require.Contains(t, sessionSummary.Output, `"user_messages":3`)
	require.Contains(t, sessionSummary.Output, `"assistant_messages":2`)
	require.Contains(t, sessionSummary.Output, `"tool_uses":1`)
	require.Contains(t, sessionSummary.Output, `"tool_results":1`)
	require.Contains(t, sessionSummary.Output, `"tool_errors":1`)
	require.Contains(t, sessionSummary.Output, `"text_rendered":true`)
	require.Contains(t, sessionSummary.Output, `"has_current_work":true`)
	require.Contains(t, sessionSummary.Output, `"has_last_assistant":true`)
	require.Contains(t, sessionSummary.Output, `"has_tool_summary":true`)
	require.Contains(t, sessionSummary.Output, `"has_tool_result_counts":true`)

	contextView := findScenario(t, report, "context_view_roundtrip")
	require.True(t, contextView.OK)
	require.Equal(t, "context-management", contextView.Category)
	require.Equal(t, 0, contextView.ToolCalls)
	require.Equal(t, 4, contextView.RequestCount)
	require.Equal(t, "context view harness ok", contextView.FinalMessage)
	require.Contains(t, contextView.Output, `"kind":"context_view"`)
	require.Contains(t, contextView.Output, `"memory_files":1`)
	require.Contains(t, contextView.Output, `"focused_paths":1`)
	require.Contains(t, contextView.Output, `"prompt_lines":2`)
	require.Contains(t, contextView.Output, `"plan_active":true`)
	require.Contains(t, contextView.Output, `"text_rendered":true`)
	require.Contains(t, contextView.Output, `"html_rendered":true`)
	require.Contains(t, contextView.Output, `"git_dirty_signal":true`)
	require.Contains(t, contextView.Output, `"plan_mode_signal":true`)
	require.Contains(t, contextView.Output, `"warning_preserved":true`)
	memoryCategory := findCategory(t, report, "context-management")
	require.True(t, memoryCategory.OK)
	require.Equal(t, 4, memoryCategory.Total)
	require.ElementsMatch(t, []string{"context_view_roundtrip", "memory_lifecycle_roundtrip", "prompt_directory_reference_roundtrip", "session_summary_roundtrip"}, memoryCategory.Scenarios)

	themeLifecycle := findScenario(t, report, "theme_lifecycle_roundtrip")
	require.True(t, themeLifecycle.OK)
	require.Equal(t, "preferences", themeLifecycle.Category)
	require.Equal(t, 0, themeLifecycle.ToolCalls)
	require.Equal(t, 5, themeLifecycle.RequestCount)
	require.Equal(t, "theme lifecycle harness ok", themeLifecycle.FinalMessage)
	require.Contains(t, themeLifecycle.Output, `"kind":"theme_lifecycle"`)
	require.Contains(t, themeLifecycle.Output, `"initial":"default"`)
	require.Contains(t, themeLifecycle.Output, `"set":"dark"`)
	require.Contains(t, themeLifecycle.Output, `"status":"dark"`)
	require.Contains(t, themeLifecycle.Output, `"cleared":"default"`)
	require.Contains(t, themeLifecycle.Output, `"clear_previous":"dark"`)
	require.Contains(t, themeLifecycle.Output, `"path_persisted":true`)
	require.Contains(t, themeLifecycle.Output, `"text_rendered":true`)

	interfacePreferences := findScenario(t, report, "interface_preferences_roundtrip")
	require.True(t, interfacePreferences.OK)
	require.Equal(t, "preferences", interfacePreferences.Category)
	require.Equal(t, 0, interfacePreferences.ToolCalls)
	require.Equal(t, 8, interfacePreferences.RequestCount)
	require.Equal(t, "interface preferences harness ok", interfacePreferences.FinalMessage)
	require.Contains(t, interfacePreferences.Output, `"kind":"interface_preferences"`)
	require.Contains(t, interfacePreferences.Output, `"set":"Japanese"`)
	require.Contains(t, interfacePreferences.Output, `"status":"Japanese"`)
	require.Contains(t, interfacePreferences.Output, `"clear_previous":"Japanese"`)
	require.Contains(t, interfacePreferences.Output, `"initial_enabled":false`)
	require.Contains(t, interfacePreferences.Output, `"set":"vim"`)
	require.Contains(t, interfacePreferences.Output, `"status":"vim"`)
	require.Contains(t, interfacePreferences.Output, `"cleared":"default"`)
	require.Contains(t, interfacePreferences.Output, `"path_persisted":true`)
	require.Contains(t, interfacePreferences.Output, `"text_rendered":true`)

	privacyKeybindings := findScenario(t, report, "privacy_keybindings_roundtrip")
	require.True(t, privacyKeybindings.OK)
	require.Equal(t, "preferences", privacyKeybindings.Category)
	require.Equal(t, 0, privacyKeybindings.ToolCalls)
	require.Equal(t, 11, privacyKeybindings.RequestCount)
	require.Equal(t, "privacy keybindings harness ok", privacyKeybindings.FinalMessage)
	require.Contains(t, privacyKeybindings.Output, `"kind":"privacy_keybindings"`)
	require.Contains(t, privacyKeybindings.Output, `"initial_prompt_history":true`)
	require.Contains(t, privacyKeybindings.Output, `"set_prompt_history":false`)
	require.Contains(t, privacyKeybindings.Output, `"status_prompt_history":false`)
	require.Contains(t, privacyKeybindings.Output, `"cleared_prompt_history":true`)
	require.Contains(t, privacyKeybindings.Output, `"created":true`)
	require.Contains(t, privacyKeybindings.Output, `"valid":true`)
	require.Contains(t, privacyKeybindings.Output, `"contexts":4`)
	require.Contains(t, privacyKeybindings.Output, `"bindings":19`)
	require.Contains(t, privacyKeybindings.Output, `"resolved":true`)
	require.Contains(t, privacyKeybindings.Output, `"source":"user"`)

	browserNotifications := findScenario(t, report, "browser_notifications_roundtrip")
	require.True(t, browserNotifications.OK)
	require.Equal(t, "preferences", browserNotifications.Category)
	require.Equal(t, 0, browserNotifications.ToolCalls)
	require.Equal(t, 13, browserNotifications.RequestCount)
	require.Equal(t, "browser notifications harness ok", browserNotifications.FinalMessage)
	require.Contains(t, browserNotifications.Output, `"kind":"browser_notifications"`)
	require.Contains(t, browserNotifications.Output, `"mcp_server":"claude-in-chrome"`)
	require.Contains(t, browserNotifications.Output, `"set":true`)
	require.Contains(t, browserNotifications.Output, `"set":false`)
	require.Contains(t, browserNotifications.Output, `"cleared":false`)
	require.Contains(t, browserNotifications.Output, `"cleared":true`)
	require.Contains(t, browserNotifications.Output, `"path_persisted":true`)
	require.Contains(t, browserNotifications.Output, `"text_rendered":true`)

	modelRuntime := findScenario(t, report, "model_runtime_preferences_roundtrip")
	require.True(t, modelRuntime.OK)
	require.Equal(t, "model-runtime", modelRuntime.Category)
	require.Equal(t, 0, modelRuntime.ToolCalls)
	require.Equal(t, 13, modelRuntime.RequestCount)
	require.Equal(t, "model runtime preferences harness ok", modelRuntime.FinalMessage)
	require.Contains(t, modelRuntime.Output, `"kind":"model_runtime_preferences"`)
	require.Contains(t, modelRuntime.Output, `"initial":"auto"`)
	require.Contains(t, modelRuntime.Output, `"set":"high"`)
	require.Contains(t, modelRuntime.Output, `"status":"high"`)
	require.Contains(t, modelRuntime.Output, `"clear_previous":"high"`)
	require.Contains(t, modelRuntime.Output, `"set":true`)
	require.Contains(t, modelRuntime.Output, `"clear_previous":true`)
	require.Contains(t, modelRuntime.Output, `"set":0.7`)
	require.Contains(t, modelRuntime.Output, `"path_persisted":true`)
	require.Contains(t, modelRuntime.Output, `"text_rendered":true`)
	modelRuntimeCategory := findCategory(t, report, "model-runtime")
	require.True(t, modelRuntimeCategory.OK)
	require.Equal(t, 3, modelRuntimeCategory.Total)
	require.ElementsMatch(t, []string{"budget_lifecycle_roundtrip", "model_runtime_preferences_roundtrip", "model_selection_roundtrip"}, modelRuntimeCategory.Scenarios)

	modelSelection := findScenario(t, report, "model_selection_roundtrip")
	require.True(t, modelSelection.OK)
	require.Equal(t, "model-runtime", modelSelection.Category)
	require.Equal(t, 0, modelSelection.ToolCalls)
	require.Equal(t, 5, modelSelection.RequestCount)
	require.Equal(t, "model selection harness ok", modelSelection.FinalMessage)
	require.Contains(t, modelSelection.Output, `"kind":"model_selection"`)
	require.Contains(t, modelSelection.Output, `"set":"kimi"`)
	require.Contains(t, modelSelection.Output, `"status":"kimi"`)
	require.Contains(t, modelSelection.Output, `"resolved":"kimi-k2.5"`)
	require.Contains(t, modelSelection.Output, `"provider":"dashscope"`)
	require.Contains(t, modelSelection.Output, `"requires_provider_request":false`)
	require.Contains(t, modelSelection.Output, `"path_persisted":true`)
	require.Contains(t, modelSelection.Output, `"text_rendered":true`)

	budgetLifecycle := findScenario(t, report, "budget_lifecycle_roundtrip")
	require.True(t, budgetLifecycle.OK)
	require.Equal(t, "model-runtime", budgetLifecycle.Category)
	require.Equal(t, 0, budgetLifecycle.ToolCalls)
	require.Equal(t, 5, budgetLifecycle.RequestCount)
	require.Equal(t, "budget lifecycle harness ok", budgetLifecycle.FinalMessage)
	require.Contains(t, budgetLifecycle.Output, `"kind":"budget_lifecycle"`)
	require.Contains(t, budgetLifecycle.Output, `"initial_tokens":4096`)
	require.Contains(t, budgetLifecycle.Output, `"initial_turns":8`)
	require.Contains(t, budgetLifecycle.Output, `"set_tokens":8192`)
	require.Contains(t, budgetLifecycle.Output, `"set_turns":12`)
	require.Contains(t, budgetLifecycle.Output, `"reset_tokens":4096`)
	require.Contains(t, budgetLifecycle.Output, `"reset_turns":8`)
	require.Contains(t, budgetLifecycle.Output, `"path_persisted":true`)
	require.Contains(t, budgetLifecycle.Output, `"text_rendered":true`)

	authCredentials := findScenario(t, report, "auth_credentials_roundtrip")
	require.True(t, authCredentials.OK)
	require.Equal(t, "auth", authCredentials.Category)
	require.Equal(t, 0, authCredentials.ToolCalls)
	require.Equal(t, 8, authCredentials.RequestCount)
	require.Equal(t, "auth credentials harness ok", authCredentials.FinalMessage)
	require.Contains(t, authCredentials.Output, `"kind":"auth_credentials"`)
	require.Contains(t, authCredentials.Output, `"source":"config"`)
	require.Contains(t, authCredentials.Output, `"redacted":true`)
	require.Contains(t, authCredentials.Output, `"api_key_method":"api_key"`)
	require.Contains(t, authCredentials.Output, `"token_method":"auth_token"`)
	require.Contains(t, authCredentials.Output, `"token_ready":true`)
	require.Contains(t, authCredentials.Output, `"secret_redacted":true`)
	require.Contains(t, authCredentials.Output, `"env_vars":3`)
	authCategory := findCategory(t, report, "auth")
	require.True(t, authCategory.OK)
	require.Equal(t, 1, authCategory.Total)
	require.ElementsMatch(t, []string{"auth_credentials_roundtrip"}, authCategory.Scenarios)
	preferencesCategory := findCategory(t, report, "preferences")
	require.True(t, preferencesCategory.OK)
	require.Equal(t, 4, preferencesCategory.Total)
	require.ElementsMatch(t, []string{"browser_notifications_roundtrip", "interface_preferences_roundtrip", "privacy_keybindings_roundtrip", "theme_lifecycle_roundtrip"}, preferencesCategory.Scenarios)

	outputStyle := findScenario(t, report, "output_style_lifecycle_roundtrip")
	require.True(t, outputStyle.OK)
	require.Equal(t, "interactive-ui", outputStyle.Category)
	require.Equal(t, 0, outputStyle.ToolCalls)
	require.Equal(t, 4, outputStyle.RequestCount)
	require.Equal(t, "output style lifecycle harness ok", outputStyle.FinalMessage)
	require.Contains(t, outputStyle.Output, `"kind":"output_style_lifecycle"`)
	require.Contains(t, outputStyle.Output, `"builtin_concise":true`)
	require.Contains(t, outputStyle.Output, `"workspace_override":true`)
	require.Contains(t, outputStyle.Output, `"active":"calm"`)
	require.Contains(t, outputStyle.Output, `"injected":true`)
	require.Contains(t, outputStyle.Output, `"empty":true`)

	diagnostics := findScenario(t, report, "diagnostics_status_roundtrip")
	require.True(t, diagnostics.OK)
	require.Equal(t, "diagnostics", diagnostics.Category)
	require.Equal(t, 0, diagnostics.ToolCalls)
	require.Equal(t, 3, diagnostics.RequestCount)
	require.Equal(t, "diagnostics status harness ok", diagnostics.FinalMessage)
	require.Contains(t, diagnostics.Output, `"kind":"diagnostics_status"`)
	require.Contains(t, diagnostics.Output, `"workspace_name"`)
	require.Contains(t, diagnostics.Output, `"memory_file_count":1`)
	require.Contains(t, diagnostics.Output, `"permission_unknowns":0`)
	require.Contains(t, diagnostics.Output, `"git_head_sha":"1234567890abcdef1234567890abcdef12345678"`)
	require.Contains(t, diagnostics.Output, `"git_head_ref":"main"`)
	require.Contains(t, diagnostics.Output, `"git_detached":false`)
	require.Contains(t, diagnostics.Output, `"base_commit_status":"matches"`)
	require.Contains(t, diagnostics.Output, `"base_commit_matches":true`)
	require.Contains(t, diagnostics.Output, `"boot_head_ref":"main"`)
	require.Contains(t, diagnostics.Output, `"boot_base_commit":"matches"`)
	require.Contains(t, diagnostics.Output, `"has_auth":true`)
	require.Contains(t, diagnostics.Output, `"has_hooks":true`)
	require.Contains(t, diagnostics.Output, `"has_sandbox":true`)
	require.Contains(t, diagnostics.Output, `"git_head_ref":"main"`)
	require.Contains(t, diagnostics.Output, `"git_freshness":"fresh"`)
	require.Contains(t, diagnostics.Output, `"git_base_commit":"no_expected_base"`)
	require.Contains(t, diagnostics.Output, `"status_action":"status"`)
	require.Contains(t, diagnostics.Output, `"snippet":true`)
	diagnosticsCategory := findCategory(t, report, "diagnostics")
	require.True(t, diagnosticsCategory.OK)
	require.Equal(t, 1, diagnosticsCategory.Total)
	require.ElementsMatch(t, []string{"diagnostics_status_roundtrip"}, diagnosticsCategory.Scenarios)

	statusline := findScenario(t, report, "statusline_cli_roundtrip")
	require.True(t, statusline.OK)
	require.Equal(t, "interactive-ui", statusline.Category)
	require.Equal(t, 0, statusline.ToolCalls)
	require.Equal(t, 2, statusline.RequestCount)
	require.Equal(t, "statusline cli harness ok", statusline.FinalMessage)
	require.Contains(t, statusline.Output, `"kind":"statusline_cli"`)
	require.Contains(t, statusline.Output, `"source":"codog"`)
	require.Contains(t, statusline.Output, `"model":"claude-statusline"`)
	require.Contains(t, statusline.Output, `"fast_mode":true`)
	require.Contains(t, statusline.Output, `"permission_mode":"read-only"`)
	require.Contains(t, statusline.Output, `"session_count":0`)
	require.Contains(t, statusline.Output, `"git_available":false`)
	require.Contains(t, statusline.Output, `"text_matches":true`)

	askUserQuestion := findScenario(t, report, "ask_user_question_roundtrip")
	require.True(t, askUserQuestion.OK)
	require.Equal(t, "interactive-ui", askUserQuestion.Category)
	require.Equal(t, []string{"ask_user_question", "ask_user_question"}, askUserQuestion.ToolUses)
	require.Equal(t, 2, askUserQuestion.ToolCalls)
	require.Equal(t, 0, askUserQuestion.ToolErrorCount)
	require.Contains(t, askUserQuestion.Output, `"answer": "beta"`)
	require.Contains(t, askUserQuestion.Output, `"answer": "yes"`)
	require.Contains(t, askUserQuestion.Output, "ask user question harness ok")
	interactiveUI := findCategory(t, report, "interactive-ui")
	require.True(t, interactiveUI.OK)
	require.Equal(t, 4, interactiveUI.Total)
	require.ElementsMatch(t, []string{"ask_user_question_roundtrip", "output_style_lifecycle_roundtrip", "statusline_cli_roundtrip", "tui_prompt_completion_roundtrip"}, interactiveUI.Scenarios)

	runtimeOutputTools := findScenario(t, report, "runtime_output_tools_roundtrip")
	require.True(t, runtimeOutputTools.OK)
	require.Equal(t, "runtime-tools", runtimeOutputTools.Category)
	require.Equal(t, []string{"brief", "send_user_message", "structured_output", "sleep"}, runtimeOutputTools.ToolUses)
	require.Equal(t, 4, runtimeOutputTools.ToolCalls)
	require.Equal(t, 0, runtimeOutputTools.ToolErrorCount)
	require.Contains(t, runtimeOutputTools.Output, `"message": "Brief parity message"`)
	require.Contains(t, runtimeOutputTools.Output, `"structured_output": {`)
	require.Contains(t, runtimeOutputTools.Output, "runtime output tools harness ok")
	runtimeTools := findCategory(t, report, "runtime-tools")
	require.True(t, runtimeTools.OK)
	require.Equal(t, 2, runtimeTools.Total)
	require.ElementsMatch(t, []string{"repl_runtime_roundtrip", "runtime_output_tools_roundtrip"}, runtimeTools.Scenarios)

	replRuntime := findScenario(t, report, "repl_runtime_roundtrip")
	require.True(t, replRuntime.OK)
	require.Equal(t, "runtime-tools", replRuntime.Category)
	require.Equal(t, []string{"repl", "repl"}, replRuntime.ToolUses)
	require.Equal(t, 2, replRuntime.ToolCalls)
	require.Equal(t, 0, replRuntime.ToolErrorCount)
	require.Contains(t, replRuntime.Output, `"timed_out": true`)
	require.Contains(t, replRuntime.Output, "repl runtime harness ok")

	configPrecedence := findScenario(t, report, "config_precedence_roundtrip")
	require.True(t, configPrecedence.OK)
	require.Equal(t, 0, configPrecedence.ToolCalls)
	require.Contains(t, configPrecedence.Output, "config precedence harness ok")

	configValidationStatus := findScenario(t, report, "config_validation_status_roundtrip")
	require.True(t, configValidationStatus.OK)
	require.Equal(t, "config", configValidationStatus.Category)
	require.Equal(t, 0, configValidationStatus.ToolCalls)
	require.Equal(t, "config validation status harness ok", configValidationStatus.FinalMessage)
	require.Contains(t, configValidationStatus.Output, `"config_validation"`)
	require.Contains(t, configValidationStatus.Output, `"warning_count": 1`)

	providerRouting := findScenario(t, report, "provider_routing_roundtrip")
	require.True(t, providerRouting.OK)
	require.Equal(t, "provider-routing", providerRouting.Category)
	require.Equal(t, 0, providerRouting.ToolCalls)
	require.Equal(t, 4, providerRouting.RequestCount)
	require.Equal(t, "provider routing harness ok", providerRouting.FinalMessage)
	require.Contains(t, providerRouting.Output, `"name": "openai-prefixed-model"`)
	require.Contains(t, providerRouting.Output, `"wire_model": "gpt-4.1-mini"`)
	require.Contains(t, providerRouting.Output, `"provider_source": "OLLAMA_HOST"`)
	require.Contains(t, providerRouting.Output, `"auth_source": "OPENAI_BASE_URL"`)
	require.Contains(t, providerRouting.Output, `"provider": "dashscope"`)
	providerRoutingCategory := findCategory(t, report, "provider-routing")
	require.True(t, providerRoutingCategory.OK)
	require.Equal(t, 1, providerRoutingCategory.Total)
	require.ElementsMatch(t, []string{"provider_routing_roundtrip"}, providerRoutingCategory.Scenarios)

	sessionResume := findScenario(t, report, "session_resume_jsonl_roundtrip")
	require.True(t, sessionResume.OK)
	require.Equal(t, 0, sessionResume.ToolCalls)
	require.Equal(t, 1, sessionResume.RequestCount)
	require.Equal(t, []int{3}, sessionResume.RequestMessageCounts)
	require.Equal(t, 4, sessionResume.MessageCount)
	require.Contains(t, sessionResume.Output, "resume harness ok")

	sessionExport := findScenario(t, report, "session_export_path_safety_roundtrip")
	require.True(t, sessionExport.OK)
	require.Equal(t, "session-resume", sessionExport.Category)
	require.Equal(t, "session export path safety harness ok", sessionExport.FinalMessage)
	require.Contains(t, sessionExport.Output, `"file": "`)
	require.Contains(t, sessionExport.Output, `"format": "markdown"`)

	pluginLifecycle := findScenario(t, report, "plugin_lifecycle_roundtrip")
	require.True(t, pluginLifecycle.OK)
	require.Equal(t, 0, pluginLifecycle.ToolCalls)
	require.Contains(t, pluginLifecycle.Output, "plugin lifecycle harness ok")

	taskLifecycle := findScenario(t, report, "task_lifecycle_roundtrip")
	require.True(t, taskLifecycle.OK)
	require.Equal(t, "background-agents", taskLifecycle.Category)
	require.Equal(t, 9, taskLifecycle.ToolCalls)
	require.Equal(t, 9, taskLifecycle.RequestCount)
	require.Equal(t, []string{
		"task_create",
		"task_status",
		"task_output",
		"task_update",
		"task_get",
		"task_list",
		"task_create",
		"task_output",
		"task_stop",
	}, taskLifecycle.ToolUses)
	require.Equal(t, "task lifecycle harness ok", taskLifecycle.FinalMessage)
	require.Contains(t, taskLifecycle.Output, `"kind":"task_lifecycle"`)
	require.Contains(t, taskLifecycle.Output, `"stdout":"task-output"`)
	require.Contains(t, taskLifecycle.Output, `"message":"review logs"`)
	require.Contains(t, taskLifecycle.Output, `"listed_total":1`)
	require.Contains(t, taskLifecycle.Output, `"status":"stopped"`)

	taskPacket := findScenario(t, report, "task_packet_roundtrip")
	require.True(t, taskPacket.OK)
	require.Equal(t, "task-packets", taskPacket.Category)
	require.Equal(t, 4, taskPacket.ToolCalls)
	require.Equal(t, 4, taskPacket.RequestCount)
	require.Equal(t, []string{"run_task_packet", "task_output", "task_get", "task_stop"}, taskPacket.ToolUses)
	require.Equal(t, "task packet harness ok", taskPacket.FinalMessage)
	require.Contains(t, taskPacket.Output, `"kind":"task_packet_roundtrip"`)
	require.Contains(t, taskPacket.Output, `"scope":"module"`)
	require.Contains(t, taskPacket.Output, `"scope_path":"internal/taskpacket"`)
	require.Contains(t, taskPacket.Output, `"provider":"anthropic"`)
	require.Contains(t, taskPacket.Output, `"verification_steps":1`)
	require.Contains(t, taskPacket.Output, `"stopped":"stopped"`)
	taskPackets := findCategory(t, report, "task-packets")
	require.True(t, taskPackets.OK)
	require.Equal(t, 1, taskPackets.Total)
	require.Equal(t, []string{"task_packet_roundtrip"}, taskPackets.Scenarios)

	teamCron := findScenario(t, report, "team_cron_lifecycle_roundtrip")
	require.True(t, teamCron.OK)
	require.Equal(t, "team-cron", teamCron.Category)
	require.Equal(t, 7, teamCron.ToolCalls)
	require.Equal(t, 7, teamCron.RequestCount)
	require.Equal(t, []string{
		"team_create",
		"team_list",
		"team_get",
		"team_delete",
		"cron_create",
		"cron_list",
		"cron_delete",
	}, teamCron.ToolUses)
	require.Equal(t, "team cron lifecycle harness ok", teamCron.FinalMessage)
	require.Contains(t, teamCron.Output, `"kind":"team_cron_lifecycle"`)
	require.Contains(t, teamCron.Output, `"task_count":2`)
	require.Contains(t, teamCron.Output, `"stopped_tasks":2`)
	require.Contains(t, teamCron.Output, `"schedule":"0 9 * * 1"`)
	require.Contains(t, teamCron.Output, `"deleted":"deleted"`)
	teamCronCategory := findCategory(t, report, "team-cron")
	require.True(t, teamCronCategory.OK)
	require.Equal(t, 1, teamCronCategory.Total)
	require.Equal(t, []string{"team_cron_lifecycle_roundtrip"}, teamCronCategory.Scenarios)

	workerLifecycle := findScenario(t, report, "worker_lifecycle_roundtrip")
	require.True(t, workerLifecycle.OK)
	require.Equal(t, "workers", workerLifecycle.Category)
	require.Equal(t, 11, workerLifecycle.ToolCalls)
	require.Equal(t, 11, workerLifecycle.RequestCount)
	require.Equal(t, []string{
		"worker_create",
		"worker_list",
		"worker_await_ready",
		"worker_observe",
		"worker_resolve_trust",
		"worker_send_prompt",
		"worker_get",
		"worker_restart",
		"worker_observe_completion",
		"worker_startup_timeout",
		"worker_terminate",
	}, workerLifecycle.ToolUses)
	require.Equal(t, "worker lifecycle harness ok", workerLifecycle.FinalMessage)
	require.Contains(t, workerLifecycle.Output, `"kind":"worker_lifecycle"`)
	require.Contains(t, workerLifecycle.Output, `"trust_resolved":true`)
	require.Contains(t, workerLifecycle.Output, `"completion_status":"finished"`)
	require.Contains(t, workerLifecycle.Output, `"startup_failure":"trust_required"`)
	require.Contains(t, workerLifecycle.Output, `"terminal_status":"terminated"`)
	workers := findCategory(t, report, "workers")
	require.True(t, workers.OK)
	require.Equal(t, 1, workers.Total)
	require.Equal(t, []string{"worker_lifecycle_roundtrip"}, workers.Scenarios)

	recoveryLifecycle := findScenario(t, report, "recovery_lifecycle_roundtrip")
	require.True(t, recoveryLifecycle.OK)
	require.Equal(t, "recovery", recoveryLifecycle.Category)
	require.Equal(t, 6, recoveryLifecycle.ToolCalls)
	require.Equal(t, 6, recoveryLifecycle.RequestCount)
	require.Equal(t, []string{
		"recovery_recipe",
		"recovery_status",
		"recovery_attempt",
		"recovery_attempt",
		"recovery_attempt",
		"recovery_status",
	}, recoveryLifecycle.ToolUses)
	require.Equal(t, "recovery lifecycle harness ok", recoveryLifecycle.FinalMessage)
	require.Contains(t, recoveryLifecycle.Output, `"kind":"recovery_lifecycle"`)
	require.Contains(t, recoveryLifecycle.Output, `"first_result":"recovered"`)
	require.Contains(t, recoveryLifecycle.Output, `"second_result":"escalation_required"`)
	require.Contains(t, recoveryLifecycle.Output, `"partial_result":"partial_recovery"`)
	require.Contains(t, recoveryLifecycle.Output, `"stale_state":"exhausted"`)
	require.Contains(t, recoveryLifecycle.Output, `"partial_state":"failed"`)
	require.Contains(t, recoveryLifecycle.Output, `"ledger_entries":2`)
	recoveryCategory := findCategory(t, report, "recovery")
	require.True(t, recoveryCategory.OK)
	require.Equal(t, 1, recoveryCategory.Total)
	require.Equal(t, []string{"recovery_lifecycle_roundtrip"}, recoveryCategory.Scenarios)

	nudgeDedupe := findScenario(t, report, "nudge_ack_dedupe_roundtrip")
	require.True(t, nudgeDedupe.OK)
	require.Equal(t, "nudge", nudgeDedupe.Category)
	require.Equal(t, 5, nudgeDedupe.ToolCalls)
	require.Equal(t, 5, nudgeDedupe.RequestCount)
	require.Equal(t, []string{"nudge", "nudge", "nudge", "nudge", "nudge"}, nudgeDedupe.ToolUses)
	require.Equal(t, "nudge ack dedupe harness ok", nudgeDedupe.FinalMessage)
	require.Contains(t, nudgeDedupe.Output, `"kind":"nudge_ack_dedupe"`)
	require.Contains(t, nudgeDedupe.Output, `"first_state":"new_nudge"`)
	require.Contains(t, nudgeDedupe.Output, `"retry_state":"retry_nudge"`)
	require.Contains(t, nudgeDedupe.Output, `"stale_state":"stale_duplicate"`)
	require.Contains(t, nudgeDedupe.Output, `"already_acknowledged":true`)
	nudgeCategory := findCategory(t, report, "nudge")
	require.True(t, nudgeCategory.OK)
	require.Equal(t, 1, nudgeCategory.Total)
	require.Equal(t, []string{"nudge_ack_dedupe_roundtrip"}, nudgeCategory.Scenarios)

	provisionalStatus := findScenario(t, report, "provisional_status_escalation_roundtrip")
	require.True(t, provisionalStatus.OK)
	require.Equal(t, "status-events", provisionalStatus.Category)
	require.Equal(t, 3, provisionalStatus.ToolCalls)
	require.Equal(t, 3, provisionalStatus.RequestCount)
	require.Equal(t, []string{"provisional_status", "provisional_status", "provisional_status"}, provisionalStatus.ToolUses)
	require.Equal(t, "provisional status escalation harness ok", provisionalStatus.FinalMessage)
	require.Contains(t, provisionalStatus.Output, `"kind":"provisional_status_escalation"`)
	require.Contains(t, provisionalStatus.Output, `"first_decision":"new_provisional"`)
	require.Contains(t, provisionalStatus.Output, `"fresh_decision":"suppressed_duplicate"`)
	require.Contains(t, provisionalStatus.Output, `"fresh_exposed":false`)
	require.Contains(t, provisionalStatus.Output, `"stale_decision":"stale_provisional"`)
	require.Contains(t, provisionalStatus.Output, `"stale_kind":"provisional_status_stale"`)
	require.Contains(t, provisionalStatus.Output, `"stale_signal":"blocker"`)
	require.Contains(t, provisionalStatus.Output, `"policy_id":"dogfood-fast-ttl"`)
	require.Contains(t, provisionalStatus.Output, `"stale_for_seconds":60`)
	statusEventsCategory := findCategory(t, report, "status-events")
	require.True(t, statusEventsCategory.OK)
	require.Equal(t, 1, statusEventsCategory.Total)
	require.Equal(t, []string{"provisional_status_escalation_roundtrip"}, statusEventsCategory.Scenarios)

	roadmapPinpoint := findScenario(t, report, "roadmap_pinpoint_lifecycle_roundtrip")
	require.True(t, roadmapPinpoint.OK)
	require.Equal(t, "roadmap", roadmapPinpoint.Category)
	require.Equal(t, 5, roadmapPinpoint.ToolCalls)
	require.Equal(t, 5, roadmapPinpoint.RequestCount)
	require.Equal(t, []string{"roadmap_pinpoint", "roadmap_pinpoint", "roadmap_pinpoint", "roadmap_pinpoint", "roadmap_pinpoint"}, roadmapPinpoint.ToolUses)
	require.Equal(t, "roadmap pinpoint lifecycle harness ok", roadmapPinpoint.FinalMessage)
	require.Contains(t, roadmapPinpoint.Output, `"kind":"roadmap_pinpoint_lifecycle"`)
	require.Contains(t, roadmapPinpoint.Output, `"first_action":"new_roadmap_filing"`)
	require.Contains(t, roadmapPinpoint.Output, `"update_action":"roadmap_update"`)
	require.Contains(t, roadmapPinpoint.Output, `"update_state":"in_progress"`)
	require.Contains(t, roadmapPinpoint.Output, `"closed_state":"done"`)
	require.Contains(t, roadmapPinpoint.Output, `"evidence_count":2`)
	require.Contains(t, roadmapPinpoint.Output, `"priority":"p0"`)
	require.Contains(t, roadmapPinpoint.Output, `"severity":"critical"`)
	require.Contains(t, roadmapPinpoint.Output, `"impact":"operator_friction"`)
	require.Contains(t, roadmapPinpoint.Output, `"readiness":"implementation_ready"`)
	require.Contains(t, roadmapPinpoint.Output, `"implementation":1`)
	require.Contains(t, roadmapPinpoint.Output, `"item_id":"rp-`)
	roadmapCategory := findCategory(t, report, "roadmap")
	require.True(t, roadmapCategory.OK)
	require.Equal(t, 3, roadmapCategory.Total)
	require.ElementsMatch(t, []string{"roadmap_pinpoint_lifecycle_roundtrip", "report_atomic_update_roundtrip", "report_backpressure_roundtrip"}, roadmapCategory.Scenarios)

	reportAtomicUpdate := findScenario(t, report, "report_atomic_update_roundtrip")
	require.True(t, reportAtomicUpdate.OK)
	require.Equal(t, "roadmap", reportAtomicUpdate.Category)
	require.Equal(t, 0, reportAtomicUpdate.ToolCalls)
	require.Equal(t, 2, reportAtomicUpdate.RequestCount)
	require.Equal(t, "report atomic update harness ok", reportAtomicUpdate.FinalMessage)
	require.Contains(t, reportAtomicUpdate.Output, `"kind":"report_atomic_update"`)
	require.Contains(t, reportAtomicUpdate.Output, `"message_complete":true`)
	require.Contains(t, reportAtomicUpdate.Output, `"part_indexes":[0,1,2]`)
	require.Contains(t, reportAtomicUpdate.Output, `"partial_complete":false`)

	reportBackpressure := findScenario(t, report, "report_backpressure_roundtrip")
	require.True(t, reportBackpressure.OK)
	require.Equal(t, "roadmap", reportBackpressure.Category)
	require.Equal(t, 9, reportBackpressure.ToolCalls)
	require.Equal(t, 9, reportBackpressure.RequestCount)
	require.Equal(t, []string{"roadmap_pinpoint", "report_backpressure", "report_backpressure", "report_backpressure", "roadmap_pinpoint", "report_backpressure", "report_backpressure", "report_backpressure", "report_schema"}, reportBackpressure.ToolUses)
	require.Equal(t, "report backpressure harness ok", reportBackpressure.FinalMessage)
	require.Contains(t, reportBackpressure.Output, `"kind":"report_backpressure_roundtrip"`)
	require.Contains(t, reportBackpressure.Output, `"schema_version":"codog.reporting.report.v1"`)
	require.Contains(t, reportBackpressure.Output, `"compatibility":"codog.reporting.compatibility.v1"`)
	require.Contains(t, reportBackpressure.Output, `"stable_core":`)
	require.Contains(t, reportBackpressure.Output, `"first_new":1`)
	require.Contains(t, reportBackpressure.Output, `"second_outcome":"no_change"`)
	require.Contains(t, reportBackpressure.Output, `"second_no_change":true`)
	require.Contains(t, reportBackpressure.Output, `"second_trigger":"nudge-cycle-1"`)
	require.Contains(t, reportBackpressure.Output, `"second_unchanged":1`)
	require.Contains(t, reportBackpressure.Output, `"second_collapsed":true`)
	require.Contains(t, reportBackpressure.Output, `"last_meaningful":"report-`)
	require.Contains(t, reportBackpressure.Output, `"stale_count":1`)
	require.Contains(t, reportBackpressure.Output, `"negative_count":2`)
	require.Contains(t, reportBackpressure.Output, `"negative_status":"not_observed_in_checked_scope"`)
	require.Contains(t, reportBackpressure.Output, `"negative_window":"2026-07-07T16:01:00Z/2026-07-07T16:02:00Z"`)
	require.Contains(t, reportBackpressure.Output, `"field_delta":"cleared"`)
	require.Contains(t, reportBackpressure.Output, `"invalidates":2`)
	require.Contains(t, reportBackpressure.Output, `"priority_delta":"changed"`)
	require.Contains(t, reportBackpressure.Output, `"projected":true`)
	require.Contains(t, reportBackpressure.Output, `"projected_view":"delta_brief"`)
	require.Contains(t, reportBackpressure.Output, `"projected_level":"brief"`)
	require.Contains(t, reportBackpressure.Output, `"projected_omits":`)
	require.Contains(t, reportBackpressure.Output, `"source_anchor":"`)
	require.Contains(t, reportBackpressure.Output, `"source_changed":true`)
	require.Contains(t, reportBackpressure.Output, `"latest":true`)
	require.Contains(t, reportBackpressure.Output, `"supersedes":"`)
	require.Contains(t, reportBackpressure.Output, `"schema_fields":2`)
	require.Contains(t, reportBackpressure.Output, `"first_root_claim":"hypothesis"`)
	require.Contains(t, reportBackpressure.Output, `"third_root_claim":"observed_fact"`)
	require.Contains(t, reportBackpressure.Output, `"promoted_from":"hypothesis"`)
	require.Contains(t, reportBackpressure.Output, `"third_changed":1`)

	agentMarkdown := findScenario(t, report, "agent_markdown_definition_roundtrip")
	require.True(t, agentMarkdown.OK)
	require.Equal(t, "background-agents", agentMarkdown.Category)
	require.Equal(t, 0, agentMarkdown.ToolCalls)
	require.Equal(t, "agent markdown definition harness ok", agentMarkdown.FinalMessage)
	require.Contains(t, agentMarkdown.Output, `"format": "markdown"`)
	require.Contains(t, agentMarkdown.Output, `"source": "claude"`)

	backgroundAgent := findScenario(t, report, "background_agent_run_roundtrip")
	require.True(t, backgroundAgent.OK)
	require.Equal(t, "background-agents", backgroundAgent.Category)
	require.Equal(t, 0, backgroundAgent.ToolCalls)
	require.Equal(t, 7, backgroundAgent.RequestCount)
	require.Equal(t, "background agent run harness ok", backgroundAgent.FinalMessage)
	require.Contains(t, backgroundAgent.Output, `"kind":"background_agent_run"`)
	require.Contains(t, backgroundAgent.Output, `"agent":"reviewer"`)
	require.Contains(t, backgroundAgent.Output, `"freshness":"healthy"`)
	require.Contains(t, backgroundAgent.Output, `"watch_events":["status","log"]`)
	require.Contains(t, backgroundAgent.Output, `"stopped":"stopped"`)
	require.Contains(t, backgroundAgent.Output, `"stopped_terminal":true`)
	require.Contains(t, backgroundAgent.Output, `"terminal_duplicates":1`)
	require.Contains(t, backgroundAgent.Output, `"terminal_fingerprint":"terminal:`)
	require.Contains(t, backgroundAgent.Output, `"lifecycle_reason":"active_status"`)
	require.Contains(t, backgroundAgent.Output, `"source_kind":"healthcheck"`)
	require.Contains(t, backgroundAgent.Output, `"emitter":"codog-harness"`)
	require.Contains(t, backgroundAgent.Output, `"workflow_scope":"claw-code-dogfood"`)
	require.Contains(t, backgroundAgent.Output, `"owner":"reviewer"`)
	require.Contains(t, backgroundAgent.Output, `"actionable":true`)
	require.Contains(t, backgroundAgent.Output, `"restarted":true`)
	require.Contains(t, backgroundAgent.Output, `"failed_exit_code":7`)
	backgroundAgents := findCategory(t, report, "background-agents")
	require.True(t, backgroundAgents.OK)
	require.Equal(t, 3, backgroundAgents.Total)
	require.ElementsMatch(t, []string{"task_lifecycle_roundtrip", "agent_markdown_definition_roundtrip", "background_agent_run_roundtrip"}, backgroundAgents.Scenarios)

	remoteTrigger := findScenario(t, report, "remote_trigger_roundtrip")
	require.True(t, remoteTrigger.OK)
	require.Equal(t, 1, remoteTrigger.ToolCalls)
	require.Contains(t, remoteTrigger.Output, "remote trigger harness ok")

	remoteAPI := findScenario(t, report, "remote_api_listener_roundtrip")
	require.True(t, remoteAPI.OK)
	require.Equal(t, "remote-control", remoteAPI.Category)
	require.Equal(t, 0, remoteAPI.ToolCalls)
	require.Equal(t, 3, remoteAPI.RequestCount)
	require.Contains(t, remoteAPI.Output, "remote api listener harness ok")
	remoteControl := findCategory(t, report, "remote-control")
	require.True(t, remoteControl.OK)
	require.Equal(t, 2, remoteControl.Total)
	require.ElementsMatch(t, []string{"remote_api_listener_roundtrip", "remote_trigger_roundtrip"}, remoteControl.Scenarios)

	remoteBridge := findScenario(t, report, "remote_bridge_workspace_roundtrip")
	require.True(t, remoteBridge.OK)
	require.Equal(t, "editor-bridge", remoteBridge.Category)
	require.Equal(t, 0, remoteBridge.ToolCalls)
	require.Equal(t, 16, remoteBridge.RequestCount)
	require.Equal(t, "remote bridge workspace harness ok", remoteBridge.FinalMessage)
	require.Contains(t, remoteBridge.Output, `"kind":"remote_bridge_workspace"`)
	require.Contains(t, remoteBridge.Output, `"path_rejected":true`)
	require.Contains(t, remoteBridge.Output, `"message_appended":true`)
	require.Contains(t, remoteBridge.Output, `"token_rejected":true`)
	require.Contains(t, remoteBridge.Output, `"selection":true`)

	mcpLifecycle := findScenario(t, report, "mcp_lifecycle_roundtrip")
	require.True(t, mcpLifecycle.OK)
	require.Equal(t, "mcp-lifecycle", mcpLifecycle.Category)
	require.Equal(t, 1, mcpLifecycle.ToolCalls)
	require.Equal(t, []string{"mcp.echo"}, mcpLifecycle.ToolUses)
	require.Equal(t, 4, mcpLifecycle.RequestCount)
	require.Contains(t, mcpLifecycle.Output, `"kind":"mcp_show"`)
	require.Contains(t, mcpLifecycle.Output, `"phase":"ready"`)
	require.Contains(t, mcpLifecycle.Output, "mcp lifecycle harness ok")

	mcpToolHook := findScenario(t, report, "mcp_tool_hook_roundtrip")
	require.True(t, mcpToolHook.OK)
	require.Equal(t, "mcp-lifecycle", mcpToolHook.Category)
	require.Equal(t, 1, mcpToolHook.ToolCalls)
	require.Equal(t, []string{"mcp__workflow__echo"}, mcpToolHook.ToolUses)
	require.Contains(t, mcpToolHook.Output, "mcp tool hook harness ok")
	mcpCategory := findCategory(t, report, "mcp-lifecycle")
	require.True(t, mcpCategory.OK)
	require.Equal(t, 2, mcpCategory.Total)
	require.ElementsMatch(t, []string{"mcp_lifecycle_roundtrip", "mcp_tool_hook_roundtrip"}, mcpCategory.Scenarios)

	mcpAuth := findScenario(t, report, "mcp_auth_oauth_refresh_roundtrip")
	require.True(t, mcpAuth.OK)
	require.Equal(t, "mcp-auth", mcpAuth.Category)
	require.Equal(t, 1, mcpAuth.ToolCalls)
	require.Equal(t, []string{"mcp_auth"}, mcpAuth.ToolUses)
	require.Contains(t, mcpAuth.Output, `"refreshed": true`)
	require.Contains(t, mcpAuth.Output, `"oauth_profile": "work"`)
	require.NotContains(t, mcpAuth.Output, "new-access-token-secret")
	require.NotContains(t, mcpAuth.Output, "new-refresh-token-secret")

	mcpRecovery := findScenario(t, report, "mcp_auth_recovery_roundtrip")
	require.True(t, mcpRecovery.OK)
	require.Equal(t, "mcp-auth", mcpRecovery.Category)
	require.Equal(t, 1, mcpRecovery.ToolCalls)
	require.Equal(t, []string{"mcp_auth"}, mcpRecovery.ToolUses)
	require.Equal(t, 2, mcpRecovery.RequestCount)
	require.Equal(t, "mcp auth recovery harness ok", mcpRecovery.FinalMessage)
	require.Contains(t, mcpRecovery.Output, `"kind":"mcp_auth_recovery"`)
	require.Contains(t, mcpRecovery.Output, `"profile_configured":false`)
	require.Contains(t, mcpRecovery.Output, `"status":"unknown"`)
	require.Contains(t, mcpRecovery.Output, `"status":"error"`)
	require.Contains(t, mcpRecovery.Output, `"redacted":true`)
	mcpAuthCategory := findCategory(t, report, "mcp-auth")
	require.True(t, mcpAuthCategory.OK)
	require.Equal(t, 2, mcpAuthCategory.Total)
	require.ElementsMatch(t, []string{"mcp_auth_oauth_refresh_roundtrip", "mcp_auth_recovery_roundtrip"}, mcpAuthCategory.Scenarios)

	acp := findScenario(t, report, "acp_stdio_roundtrip")
	require.True(t, acp.OK)
	require.Equal(t, "editor-bridge", acp.Category)
	require.Equal(t, 0, acp.ToolCalls)
	require.Equal(t, 4, acp.RequestCount)
	require.Contains(t, acp.Output, `"protocolVersion"`)
	require.Contains(t, acp.Output, `"acp-harness-session"`)
	editorBridge := findCategory(t, report, "editor-bridge")
	require.True(t, editorBridge.OK)
	require.Equal(t, 2, editorBridge.Total)
	require.ElementsMatch(t, []string{"acp_stdio_roundtrip", "remote_bridge_workspace_roundtrip"}, editorBridge.Scenarios)

	autoCompact := findScenario(t, report, "auto_compact_triggered")
	require.Equal(t, "session-compaction", autoCompact.Category)
	require.True(t, autoCompact.OK)
	require.Equal(t, 1, autoCompact.Compactions)
	require.Equal(t, []int{2}, autoCompact.RequestMessageCounts)
	require.Contains(t, autoCompact.Output, "compact harness ok")

	tokenCost := findScenario(t, report, "token_cost_reporting")
	require.True(t, tokenCost.OK)
	require.Equal(t, "actual", tokenCost.UsageSummary.Source)
	require.Greater(t, tokenCost.UsageSummary.TotalTokens, 0)
	require.Greater(t, tokenCost.EstimatedCost, 0.0)
	require.Contains(t, tokenCost.Output, "token cost harness ok")
}

func TestValidateReportRejectsInconsistentReports(t *testing.T) {
	report, err := Run(context.Background())
	require.NoError(t, err)

	broken := report
	broken.SchemaVersion = "wrong"
	require.ErrorContains(t, ValidateReport(broken), "schema_version")

	broken = report
	broken.RequestCount++
	require.ErrorContains(t, ValidateReport(broken), "request_count")

	broken = report
	broken.Scenarios[0].Description = ""
	require.ErrorContains(t, ValidateReport(broken), "description is required")
}

func TestScenarioManifestMatchesRunScenarios(t *testing.T) {
	manifest := ScenarioManifest()
	require.Equal(t, ManifestSchemaVersion, manifest.SchemaVersion)
	require.Equal(t, len(scenarioOrder), manifest.ScenarioCount)
	require.Len(t, manifest.Scenarios, manifest.ScenarioCount)
	require.GreaterOrEqual(t, len(manifest.Categories), 8)
	require.Equal(t, manifest.ScenarioCount, manifestCategoryTotal(manifest.Categories))

	report, err := Run(context.Background())
	require.NoError(t, err)
	require.Equal(t, scenarioNames(report.Scenarios), manifestScenarioNames(manifest.Scenarios))

	promptDirectoryAttachment := findManifestScenario(t, manifest, "prompt_directory_attachment_roundtrip")
	require.Equal(t, "attachments", promptDirectoryAttachment.Category)
	require.Contains(t, promptDirectoryAttachment.ParityRefs, "Directory attachments")
	require.Contains(t, promptDirectoryAttachment.ParityRefs, "Workspace context")

	readFile := findManifestScenario(t, manifest, "read_file_roundtrip")
	require.Equal(t, "file-tools", readFile.Category)
	require.NotEmpty(t, readFile.Description)
	require.Contains(t, readFile.ParityRefs, "File tools")

	bashBackgroundOutput := findManifestScenario(t, manifest, "bash_background_output_roundtrip")
	require.Equal(t, "bash", bashBackgroundOutput.Category)
	require.Contains(t, bashBackgroundOutput.ParityRefs, "BashOutput tool")

	bashKill := findManifestScenario(t, manifest, "bash_kill_roundtrip")
	require.Equal(t, "bash", bashKill.Category)
	require.Contains(t, bashKill.ParityRefs, "KillBash tool")

	powerShellStdout := findManifestScenario(t, manifest, "powershell_stdout_roundtrip")
	require.Equal(t, "powershell", powerShellStdout.Category)
	require.Contains(t, powerShellStdout.ParityRefs, "PowerShell tool")

	permissionScope := findManifestScenario(t, manifest, "permission_scope_denial_roundtrip")
	require.Equal(t, "permissions", permissionScope.Category)
	require.Contains(t, permissionScope.ParityRefs, "Permission enforcement")
	require.Contains(t, permissionScope.ParityRefs, "Workspace scope denial")
	require.Contains(t, permissionScope.ParityRefs, "Tool validation")
	require.Contains(t, permissionScope.ParityRefs, "File tool denial")

	askUserQuestion := findManifestScenario(t, manifest, "ask_user_question_roundtrip")
	require.Equal(t, "interactive-ui", askUserQuestion.Category)
	require.Contains(t, askUserQuestion.ParityRefs, "AskUserQuestion tool")

	outputStyle := findManifestScenario(t, manifest, "output_style_lifecycle_roundtrip")
	require.Equal(t, "interactive-ui", outputStyle.Category)
	require.Contains(t, outputStyle.ParityRefs, "Output styles")
	require.Contains(t, outputStyle.ParityRefs, "Interactive rendering")

	diagnostics := findManifestScenario(t, manifest, "diagnostics_status_roundtrip")
	require.Equal(t, "diagnostics", diagnostics.Category)
	require.Contains(t, diagnostics.ParityRefs, "Doctor")
	require.Contains(t, diagnostics.ParityRefs, "Status diagnostics")
	require.Contains(t, diagnostics.ParityRefs, "Terminal setup")

	statusline := findManifestScenario(t, manifest, "statusline_cli_roundtrip")
	require.Equal(t, "interactive-ui", statusline.Category)
	require.Contains(t, statusline.ParityRefs, "Statusline")
	require.Contains(t, statusline.ParityRefs, "Statusline JSON")
	require.Contains(t, statusline.ParityRefs, "Statusline text")

	tuiPrompt := findManifestScenario(t, manifest, "tui_prompt_completion_roundtrip")
	require.Equal(t, "interactive-ui", tuiPrompt.Category)
	require.Contains(t, tuiPrompt.ParityRefs, "Bubble Tea TUI")

	runtimeOutputTools := findManifestScenario(t, manifest, "runtime_output_tools_roundtrip")
	require.Equal(t, "runtime-tools", runtimeOutputTools.Category)
	require.Contains(t, runtimeOutputTools.ParityRefs, "StructuredOutput tool")
	require.Contains(t, runtimeOutputTools.ParityRefs, "Sleep tool")

	replRuntime := findManifestScenario(t, manifest, "repl_runtime_roundtrip")
	require.Equal(t, "runtime-tools", replRuntime.Category)
	require.Contains(t, replRuntime.ParityRefs, "REPL tool")

	configValidationStatus := findManifestScenario(t, manifest, "config_validation_status_roundtrip")
	require.Equal(t, "config", configValidationStatus.Category)
	require.Contains(t, configValidationStatus.ParityRefs, "Config validation")
	require.Contains(t, configValidationStatus.ParityRefs, "Status diagnostics")

	sessionExport := findManifestScenario(t, manifest, "session_export_path_safety_roundtrip")
	require.Equal(t, "session-resume", sessionExport.Category)
	require.Contains(t, sessionExport.ParityRefs, "Session export")
	require.Contains(t, sessionExport.ParityRefs, "Path safety")

	remoteAPI := findManifestScenario(t, manifest, "remote_api_listener_roundtrip")
	require.Equal(t, "remote-control", remoteAPI.Category)
	require.Contains(t, remoteAPI.ParityRefs, "Control API listener")

	remoteBridge := findManifestScenario(t, manifest, "remote_bridge_workspace_roundtrip")
	require.Equal(t, "editor-bridge", remoteBridge.Category)
	require.Contains(t, remoteBridge.ParityRefs, "Workspace file operations")
	require.Contains(t, remoteBridge.ParityRefs, "Editor selection")

	acp := findManifestScenario(t, manifest, "acp_stdio_roundtrip")
	require.Equal(t, "editor-bridge", acp.Category)
	require.Contains(t, acp.ParityRefs, "JSON-RPC stdio")

	mcpLifecycle := findManifestScenario(t, manifest, "mcp_lifecycle_roundtrip")
	require.Equal(t, "mcp-lifecycle", mcpLifecycle.Category)
	require.Contains(t, mcpLifecycle.ParityRefs, "MCP lifecycle")

	mcpToolHook := findManifestScenario(t, manifest, "mcp_tool_hook_roundtrip")
	require.Equal(t, "mcp-lifecycle", mcpToolHook.Category)
	require.Contains(t, mcpToolHook.ParityRefs, "MCP tool calls")

	mcpAuth := findManifestScenario(t, manifest, "mcp_auth_oauth_refresh_roundtrip")
	require.Equal(t, "mcp-auth", mcpAuth.Category)
	require.Contains(t, mcpAuth.ParityRefs, "OAuth refresh")

	mcpRecovery := findManifestScenario(t, manifest, "mcp_auth_recovery_roundtrip")
	require.Equal(t, "mcp-auth", mcpRecovery.Category)
	require.Contains(t, mcpRecovery.ParityRefs, "Recovery actions")
	require.Contains(t, mcpRecovery.ParityRefs, "Error diagnostics")
	require.Contains(t, mcpRecovery.ParityRefs, "Token redaction")

	sandboxBypass := findManifestScenario(t, manifest, "sandbox_bypass_status_roundtrip")
	require.Equal(t, "sandbox", sandboxBypass.Category)
	require.Contains(t, sandboxBypass.ParityRefs, "Sandbox")

	policySafety := findManifestScenario(t, manifest, "policy_update_sandbox_roundtrip")
	require.Equal(t, "policy-safety", policySafety.Category)
	require.Contains(t, policySafety.ParityRefs, "Enterprise policy")
	require.Contains(t, policySafety.ParityRefs, "Signed updater")
	require.Contains(t, policySafety.ParityRefs, "Sandbox capability reporting")

	policyApproval := findManifestScenario(t, manifest, "policy_approval_roundtrip")
	require.Equal(t, "policy-safety", policyApproval.Category)
	require.Contains(t, policyApproval.ParityRefs, "Policy evaluation")
	require.Contains(t, policyApproval.ParityRefs, "Approval tokens")
	require.Contains(t, policyApproval.ParityRefs, "Delegation audit")
	require.Contains(t, policyApproval.ParityRefs, "Replay denial")
	require.Contains(t, policyApproval.ParityRefs, "Commit-scoped approval")
	require.Contains(t, policyApproval.ParityRefs, "Execution chain traceability")

	notebook := findManifestScenario(t, manifest, "notebook_read_edit_roundtrip")
	require.Equal(t, "notebook", notebook.Category)
	require.Contains(t, notebook.ParityRefs, "Notebook edit")

	webAccess := findManifestScenario(t, manifest, "web_access_roundtrip")
	require.Equal(t, "web-access", webAccess.Category)
	require.Contains(t, webAccess.ParityRefs, "Web search")

	webAccessLimits := findManifestScenario(t, manifest, "web_access_limits_roundtrip")
	require.Equal(t, "web-access", webAccessLimits.Category)
	require.Contains(t, webAccessLimits.ParityRefs, "Web fetch truncation")

	gitWorkspace := findManifestScenario(t, manifest, "git_workspace_roundtrip")
	require.Equal(t, "git-workspace", gitWorkspace.Category)
	require.Contains(t, gitWorkspace.ParityRefs, "Branch freshness")

	gitPreserveState := findManifestScenario(t, manifest, "git_preserve_state_roundtrip")
	require.Equal(t, "git-workspace", gitPreserveState.Category)
	require.Contains(t, gitPreserveState.ParityRefs, "Issue draft")
	require.Contains(t, gitPreserveState.ParityRefs, "Pull request draft")
	require.Contains(t, gitPreserveState.ParityRefs, "Share")

	worktreeLifecycle := findManifestScenario(t, manifest, "worktree_lifecycle_roundtrip")
	require.Equal(t, "git-workspace", worktreeLifecycle.Category)
	require.Contains(t, worktreeLifecycle.ParityRefs, "Worktree allocation")
	require.Contains(t, worktreeLifecycle.ParityRefs, "Worktree cleanup")

	planTodo := findManifestScenario(t, manifest, "plan_todo_roundtrip")
	require.Equal(t, "planning", planTodo.Category)
	require.Contains(t, planTodo.ParityRefs, "Plan mode")

	todoCompletion := findManifestScenario(t, manifest, "todo_completion_verification_roundtrip")
	require.Equal(t, "planning", todoCompletion.Category)
	require.Contains(t, todoCompletion.ParityRefs, "Verification reminders")

	lspStatic := findManifestScenario(t, manifest, "lsp_static_roundtrip")
	require.Equal(t, "code-intelligence", lspStatic.Category)
	require.Contains(t, lspStatic.ParityRefs, "LSP tool")

	lspMetadata := findManifestScenario(t, manifest, "lsp_cli_metadata_roundtrip")
	require.Equal(t, "code-intelligence", lspMetadata.Category)
	require.Contains(t, lspMetadata.ParityRefs, "LSP metadata")
	require.Contains(t, lspMetadata.ParityRefs, "LSP action discovery")
	require.Contains(t, lspMetadata.ParityRefs, "Interactive rendering")

	providerRouting := findManifestScenario(t, manifest, "provider_routing_roundtrip")
	require.Equal(t, "provider-routing", providerRouting.Category)
	require.Contains(t, providerRouting.ParityRefs, "OpenAI-compatible APIs")
	require.Contains(t, providerRouting.ParityRefs, "Ollama")

	workflow := findManifestScenario(t, manifest, "command_skill_template_roundtrip")
	require.Equal(t, "command-workflows", workflow.Category)
	require.Contains(t, workflow.ParityRefs, "Slash commands")
	require.Contains(t, workflow.ParityRefs, "Skills")
	require.Contains(t, workflow.ParityRefs, "Templates")

	skillActivation := findManifestScenario(t, manifest, "skill_activation_roundtrip")
	require.Equal(t, "command-workflows", skillActivation.Category)
	require.Contains(t, skillActivation.ParityRefs, "Skills")
	require.Contains(t, skillActivation.ParityRefs, "Skill activation")
	require.Contains(t, skillActivation.ParityRefs, "Preference persistence")

	onboardingBookmarks := findManifestScenario(t, manifest, "onboarding_bookmarks_roundtrip")
	require.Equal(t, "command-workflows", onboardingBookmarks.Category)
	require.Contains(t, onboardingBookmarks.ParityRefs, "Onboarding")
	require.Contains(t, onboardingBookmarks.ParityRefs, "Bookmarks")

	memoryLifecycle := findManifestScenario(t, manifest, "memory_lifecycle_roundtrip")
	require.Equal(t, "context-management", memoryLifecycle.Category)
	require.Contains(t, memoryLifecycle.ParityRefs, "Project memory")
	require.Contains(t, memoryLifecycle.ParityRefs, "Session context management")

	directoryReference := findManifestScenario(t, manifest, "prompt_directory_reference_roundtrip")
	require.Equal(t, "context-management", directoryReference.Category)
	require.Contains(t, directoryReference.ParityRefs, "Prompt references")
	require.Contains(t, directoryReference.ParityRefs, "Directory references")
	require.Contains(t, directoryReference.ParityRefs, "Workspace state")

	sessionSummary := findManifestScenario(t, manifest, "session_summary_roundtrip")
	require.Equal(t, "context-management", sessionSummary.Category)
	require.Contains(t, sessionSummary.ParityRefs, "Session summary")
	require.Contains(t, sessionSummary.ParityRefs, "Compaction summary")
	require.Contains(t, sessionSummary.ParityRefs, "Token usage")

	contextView := findManifestScenario(t, manifest, "context_view_roundtrip")
	require.Equal(t, "context-management", contextView.Category)
	require.Contains(t, contextView.ParityRefs, "Context view")
	require.Contains(t, contextView.ParityRefs, "Focused paths")
	require.Contains(t, contextView.ParityRefs, "Context signals")

	themeLifecycle := findManifestScenario(t, manifest, "theme_lifecycle_roundtrip")
	require.Equal(t, "preferences", themeLifecycle.Category)
	require.Contains(t, themeLifecycle.ParityRefs, "Theme")
	require.Contains(t, themeLifecycle.ParityRefs, "Theme persistence")
	require.Contains(t, themeLifecycle.ParityRefs, "Theme reset")

	interfacePreferences := findManifestScenario(t, manifest, "interface_preferences_roundtrip")
	require.Equal(t, "preferences", interfacePreferences.Category)
	require.Contains(t, interfacePreferences.ParityRefs, "Language preference")
	require.Contains(t, interfacePreferences.ParityRefs, "Vim mode")
	require.Contains(t, interfacePreferences.ParityRefs, "Preference persistence")

	privacyKeybindings := findManifestScenario(t, manifest, "privacy_keybindings_roundtrip")
	require.Equal(t, "preferences", privacyKeybindings.Category)
	require.Contains(t, privacyKeybindings.ParityRefs, "Privacy settings")
	require.Contains(t, privacyKeybindings.ParityRefs, "Prompt history")
	require.Contains(t, privacyKeybindings.ParityRefs, "Keybindings")

	browserNotifications := findManifestScenario(t, manifest, "browser_notifications_roundtrip")
	require.Equal(t, "preferences", browserNotifications.Category)
	require.Contains(t, browserNotifications.ParityRefs, "Chrome integration")
	require.Contains(t, browserNotifications.ParityRefs, "Notifications")
	require.Contains(t, browserNotifications.ParityRefs, "Telemetry")

	modelRuntime := findManifestScenario(t, manifest, "model_runtime_preferences_roundtrip")
	require.Equal(t, "model-runtime", modelRuntime.Category)
	require.Contains(t, modelRuntime.ParityRefs, "Reasoning effort")
	require.Contains(t, modelRuntime.ParityRefs, "Fast mode")
	require.Contains(t, modelRuntime.ParityRefs, "Temperature preference")

	modelSelection := findManifestScenario(t, manifest, "model_selection_roundtrip")
	require.Equal(t, "model-runtime", modelSelection.Category)
	require.Contains(t, modelSelection.ParityRefs, "Model preference")
	require.Contains(t, modelSelection.ParityRefs, "Model persistence")
	require.Contains(t, modelSelection.ParityRefs, "Model routing detail")

	budgetLifecycle := findManifestScenario(t, manifest, "budget_lifecycle_roundtrip")
	require.Equal(t, "model-runtime", budgetLifecycle.Category)
	require.Contains(t, budgetLifecycle.ParityRefs, "Token budget")
	require.Contains(t, budgetLifecycle.ParityRefs, "Turn limit")
	require.Contains(t, budgetLifecycle.ParityRefs, "Preference persistence")

	authCredentials := findManifestScenario(t, manifest, "auth_credentials_roundtrip")
	require.Equal(t, "auth", authCredentials.Category)
	require.Contains(t, authCredentials.ParityRefs, "Auth status")
	require.Contains(t, authCredentials.ParityRefs, "API key")
	require.Contains(t, authCredentials.ParityRefs, "Auth token")
	require.Contains(t, authCredentials.ParityRefs, "Token redaction")

	backgroundAgent := findManifestScenario(t, manifest, "background_agent_run_roundtrip")
	require.Equal(t, "background-agents", backgroundAgent.Category)
	require.Contains(t, backgroundAgent.ParityRefs, "Background tasks")
	require.Contains(t, backgroundAgent.ParityRefs, "Agent runs")
	require.Contains(t, backgroundAgent.ParityRefs, "Supervisor restarts")

	agentMarkdown := findManifestScenario(t, manifest, "agent_markdown_definition_roundtrip")
	require.Equal(t, "background-agents", agentMarkdown.Category)
	require.Contains(t, agentMarkdown.ParityRefs, "Agent definitions")
	require.Contains(t, agentMarkdown.ParityRefs, "Markdown agents")
	require.Contains(t, agentMarkdown.ParityRefs, "Claude Code migration")

	taskLifecycle := findManifestScenario(t, manifest, "task_lifecycle_roundtrip")
	require.Equal(t, "background-agents", taskLifecycle.Category)
	require.Contains(t, taskLifecycle.ParityRefs, "Task create")
	require.Contains(t, taskLifecycle.ParityRefs, "Task output")
	require.Contains(t, taskLifecycle.ParityRefs, "Task stop")

	taskPacket := findManifestScenario(t, manifest, "task_packet_roundtrip")
	require.Equal(t, "task-packets", taskPacket.Category)
	require.Contains(t, taskPacket.ParityRefs, "Task packet schema")
	require.Contains(t, taskPacket.ParityRefs, "Task packet scope resolution")
	require.Contains(t, taskPacket.ParityRefs, "Task packet persistence")

	teamCron := findManifestScenario(t, manifest, "team_cron_lifecycle_roundtrip")
	require.Equal(t, "team-cron", teamCron.Category)
	require.Contains(t, teamCron.ParityRefs, "Team tools")
	require.Contains(t, teamCron.ParityRefs, "Team task assignment")
	require.Contains(t, teamCron.ParityRefs, "Cron tools")
	require.Contains(t, teamCron.ParityRefs, "Cron lifecycle")

	workerLifecycle := findManifestScenario(t, manifest, "worker_lifecycle_roundtrip")
	require.Equal(t, "workers", workerLifecycle.Category)
	require.Contains(t, workerLifecycle.ParityRefs, "Worker tools")
	require.Contains(t, workerLifecycle.ParityRefs, "Worker trust recovery")
	require.Contains(t, workerLifecycle.ParityRefs, "Worker prompt delivery")
	require.Contains(t, workerLifecycle.ParityRefs, "Worker startup diagnostics")

	recoveryLifecycle := findManifestScenario(t, manifest, "recovery_lifecycle_roundtrip")
	require.Equal(t, "recovery", recoveryLifecycle.Category)
	require.Contains(t, recoveryLifecycle.ParityRefs, "Recovery recipes")
	require.Contains(t, recoveryLifecycle.ParityRefs, "Recovery attempts")
	require.Contains(t, recoveryLifecycle.ParityRefs, "Recovery ledger")
	require.Contains(t, recoveryLifecycle.ParityRefs, "Escalation tracking")
}

func categoryCoverageTotal(coverage []CategoryReport) int {
	total := 0
	for _, category := range coverage {
		total += category.Total
	}
	return total
}

func scenarioRequestCountTotal(scenarios []ScenarioReport) int {
	total := 0
	for _, scenario := range scenarios {
		total += scenario.RequestCount
	}
	return total
}

func manifestCategoryTotal(categories []ManifestCategory) int {
	total := 0
	for _, category := range categories {
		total += category.Count
	}
	return total
}

func manifestScenarioNames(scenarios []ManifestScenario) []string {
	names := make([]string, 0, len(scenarios))
	for _, scenario := range scenarios {
		names = append(names, scenario.Name)
	}
	return names
}

func scenarioNames(scenarios []ScenarioReport) []string {
	names := make([]string, 0, len(scenarios))
	for _, scenario := range scenarios {
		names = append(names, scenario.Name)
	}
	return names
}

func findManifestScenario(t *testing.T, manifest Manifest, name string) ManifestScenario {
	t.Helper()
	for _, scenario := range manifest.Scenarios {
		if scenario.Name == name {
			return scenario
		}
	}
	t.Fatalf("missing manifest scenario %q in %#v", name, manifest.Scenarios)
	return ManifestScenario{}
}

func findCategory(t *testing.T, report Report, category string) CategoryReport {
	t.Helper()
	for _, candidate := range report.Coverage {
		if candidate.Category == category {
			return candidate
		}
	}
	t.Fatalf("missing category %q in %#v", category, report.Coverage)
	return CategoryReport{}
}

func findScenario(t *testing.T, report Report, name string) ScenarioReport {
	t.Helper()
	for _, scenario := range report.Scenarios {
		if scenario.Name == name {
			return scenario
		}
	}
	t.Fatalf("missing scenario %q in %#v", name, report.Scenarios)
	return ScenarioReport{}
}

func failedScenarioSummaries(report Report) string {
	var builder strings.Builder
	for _, scenario := range report.Scenarios {
		if scenario.OK {
			continue
		}
		if builder.Len() > 0 {
			builder.WriteString("; ")
		}
		builder.WriteString(scenario.Name)
		if scenario.Error != "" {
			builder.WriteString(": ")
			builder.WriteString(scenario.Error)
		}
		if scenario.Output != "" {
			builder.WriteString(" output=")
			builder.WriteString(scenario.Output)
		}
	}
	if builder.Len() == 0 {
		return "no failed scenario details"
	}
	return builder.String()
}
